version: '3.8'
services:
  db:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  redis:
    image: redis:5.0.9-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}'
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
    volumes:
      - ./common/settings/rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  backend:
    image: backend
    build:
        context: .
        dockerfile: ./docker/app/Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - redis
        - rabbitmq
        - db
    environment:
      - FLASK_APP=app.manage:create_app
    env_file: ./docker.env
    volumes:
      - ./migrations/versions:/opt/migrations/versions

  socketio:
    image: socketio
    build:
        context: .
        dockerfile: ./docker/app_socketio/Dockerfile
    ports:
        - "5001:5001"
    depends_on:
        - redis
        - rabbitmq
        - db
    environment:
      - FLASK_APP=app_socketio
    env_file: ./docker.env
