version: '3.8'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    container_name: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
      - db

  backend:
    image: backend
    build:
        context: .
        dockerfile: ./docker/app/Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - db

  dramatiq:
    image: dramatiq
    build:
        context: .
        dockerfile: ./docker/app/Dockerfile.dramatiq
    ports:
        - "5002:5002"
    depends_on:
        - backend

  socketio:
    image: socketio
    build:
        context: .
        dockerfile: ./docker/app_socketio/Dockerfile
    ports:
        - "5001:5001"
    depends_on:
        - db
