"""add poll entity

Revision ID: 1c9462012bcd
Revises: 853626c2595a
Create Date: 2021-04-09 16:03:36.492163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9462012bcd'
down_revision = '853626c2595a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('allow_multiple_user_select', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('expire_after_seconds', sa.Integer(), nullable=True),
    sa.Column('is_expire', sa.Boolean(), nullable=True),
    sa.Column('poll_select_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_owner_user_id'), 'poll', ['owner_user_id'], unique=False)
    op.create_table('poll_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('poll_user_select_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_select_created_by_user_id'), 'poll_select', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_poll_select_poll_id'), 'poll_select', ['poll_id'], unique=False)
    op.create_table('poll_topic',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_topic_poll_id'), 'poll_topic', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_topic_topic_id'), 'poll_topic', ['topic_id'], unique=False)
    op.create_table('poll_user_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_select_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_select_id'], ['poll_select.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_select_poll_select_id'), 'poll_user_select', ['poll_select_id'], unique=False)
    op.create_index(op.f('ix_poll_user_select_user_id'), 'poll_user_select', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_user_select_user_id'), table_name='poll_user_select')
    op.drop_index(op.f('ix_poll_user_select_poll_select_id'), table_name='poll_user_select')
    op.drop_table('poll_user_select')
    op.drop_index(op.f('ix_poll_topic_topic_id'), table_name='poll_topic')
    op.drop_index(op.f('ix_poll_topic_poll_id'), table_name='poll_topic')
    op.drop_table('poll_topic')
    op.drop_index(op.f('ix_poll_select_poll_id'), table_name='poll_select')
    op.drop_index(op.f('ix_poll_select_created_by_user_id'), table_name='poll_select')
    op.drop_table('poll_select')
    op.drop_index(op.f('ix_poll_owner_user_id'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
