"""Add Entity tables

Revision ID: 1dcff21a69fd
Revises: b7a33bc47729
Create Date: 2021-04-11 23:11:23.316690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcff21a69fd'
down_revision = 'b7a33bc47729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('allow_multiple_user_select', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('expire_after_seconds', sa.Integer(), nullable=True),
    sa.Column('is_expire', sa.Boolean(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('poll_select_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_owner_user_id'), 'poll', ['owner_user_id'], unique=False)
    op.create_table('poll_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_report_poll_id'), 'poll_report', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_report_user_id'), 'poll_report', ['user_id'], unique=False)
    op.create_table('poll_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_bookmark_user_id'), 'poll_bookmark', ['user_id'], unique=False)
    op.create_table('poll_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_poll_id'), 'poll_comment', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_user_id'), 'poll_comment', ['user_id'], unique=False)
    op.create_table('poll_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_favorite_user_id'), 'poll_favorite', ['user_id'], unique=False)
    op.create_table('poll_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('poll_user_select_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_select_created_by_user_id'), 'poll_select', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_poll_select_poll_id'), 'poll_select', ['poll_id'], unique=False)
    op.create_table('poll_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_share_poll_id'), 'poll_share', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_share_user_id'), 'poll_share', ['user_id'], unique=False)
    op.create_table('poll_topic',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_topic_poll_id'), 'poll_topic', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_topic_topic_id'), 'poll_topic', ['topic_id'], unique=False)
    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_vote_poll_id'), 'poll_vote', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_vote_user_id'), 'poll_vote', ['user_id'], unique=False)
    op.create_table('user_seen_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_poll_poll_id'), 'user_seen_poll', ['poll_id'], unique=False)
    op.create_index(op.f('ix_user_seen_poll_user_id'), 'user_seen_poll', ['user_id'], unique=False)
    op.create_table('poll_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_favorite_user_id'), 'poll_comment_favorite', ['user_id'], unique=False)
    op.create_table('poll_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_report_comment_id'), 'poll_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_report_user_id'), 'poll_comment_report', ['user_id'], unique=False)
    op.create_table('poll_user_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_select_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_select_id'], ['poll_select.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_select_poll_select_id'), 'poll_user_select', ['poll_select_id'], unique=False)
    op.create_index(op.f('ix_poll_user_select_user_id'), 'poll_user_select', ['user_id'], unique=False)
    op.add_column('timeline', sa.Column('poll_comment_id', sa.Integer(), nullable=True))
    op.add_column('timeline', sa.Column('poll_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timeline_poll_id'), 'timeline', ['poll_id'], unique=False)
    op.create_foreign_key(None, 'timeline', 'poll_comment', ['poll_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_index(op.f('ix_timeline_poll_id'), table_name='timeline')
    op.drop_column('timeline', 'poll_id')
    op.drop_column('timeline', 'poll_comment_id')
    op.drop_index(op.f('ix_poll_user_select_user_id'), table_name='poll_user_select')
    op.drop_index(op.f('ix_poll_user_select_poll_select_id'), table_name='poll_user_select')
    op.drop_table('poll_user_select')
    op.drop_index(op.f('ix_poll_comment_report_user_id'), table_name='poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_report_comment_id'), table_name='poll_comment_report')
    op.drop_table('poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_favorite_user_id'), table_name='poll_comment_favorite')
    op.drop_table('poll_comment_favorite')
    op.drop_index(op.f('ix_user_seen_poll_user_id'), table_name='user_seen_poll')
    op.drop_index(op.f('ix_user_seen_poll_poll_id'), table_name='user_seen_poll')
    op.drop_table('user_seen_poll')
    op.drop_index(op.f('ix_poll_vote_user_id'), table_name='poll_vote')
    op.drop_index(op.f('ix_poll_vote_poll_id'), table_name='poll_vote')
    op.drop_table('poll_vote')
    op.drop_index(op.f('ix_poll_topic_topic_id'), table_name='poll_topic')
    op.drop_index(op.f('ix_poll_topic_poll_id'), table_name='poll_topic')
    op.drop_table('poll_topic')
    op.drop_index(op.f('ix_poll_share_user_id'), table_name='poll_share')
    op.drop_index(op.f('ix_poll_share_poll_id'), table_name='poll_share')
    op.drop_table('poll_share')
    op.drop_index(op.f('ix_poll_select_poll_id'), table_name='poll_select')
    op.drop_index(op.f('ix_poll_select_created_by_user_id'), table_name='poll_select')
    op.drop_table('poll_select')
    op.drop_index(op.f('ix_poll_favorite_user_id'), table_name='poll_favorite')
    op.drop_table('poll_favorite')
    op.drop_index(op.f('ix_poll_comment_user_id'), table_name='poll_comment')
    op.drop_index(op.f('ix_poll_comment_poll_id'), table_name='poll_comment')
    op.drop_table('poll_comment')
    op.drop_index(op.f('ix_poll_bookmark_user_id'), table_name='poll_bookmark')
    op.drop_table('poll_bookmark')
    op.drop_index(op.f('ix_poll_report_user_id'), table_name='poll_report')
    op.drop_index(op.f('ix_poll_report_poll_id'), table_name='poll_report')
    op.drop_table('poll_report')
    op.drop_index(op.f('ix_poll_owner_user_id'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
