"""empty message

Revision ID: 2233d56bdf1c
Revises: initial
Create Date: 2021-02-18 21:36:44.024748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2233d56bdf1c'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allow_answer_comment', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user', sa.Column('allow_article_comment', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user', sa.Column('allow_question_comment', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user', sa.Column('show_fullname_instead_of_display_name', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_fullname_instead_of_display_name')
    op.drop_column('user', 'allow_question_comment')
    op.drop_column('user', 'allow_article_comment')
    op.drop_column('user', 'allow_answer_comment')
    # ### end Alembic commands ###
