"""empty message

Revision ID: 36fcae2c39fd
Revises: 61cb61da2cf8
Create Date: 2021-04-17 23:58:21.429122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36fcae2c39fd'
down_revision = '61cb61da2cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('answer', sa.Column('user_education_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answer_user_education_id'), 'answer', ['user_education_id'], unique=False)
    op.create_foreign_key(None, 'answer', 'user_education', ['user_education_id'], ['id'], ondelete='CASCADE')
    op.add_column('poll', sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('poll', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('poll', sa.Column('select_count', sa.Integer(), nullable=False))
    op.alter_column('poll', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('poll', 'share_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('poll', 'poll_select_count')
    op.add_column('post', sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.alter_column('post', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('post', 'share_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('question', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('question_proposal', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_proposal', 'allow_voting')
    op.drop_column('question', 'allow_voting')
    op.alter_column('post', 'share_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('post', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('post', 'allow_comments')
    op.add_column('poll', sa.Column('poll_select_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('poll', 'share_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('poll', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('poll', 'select_count')
    op.drop_column('poll', 'allow_voting')
    op.drop_column('poll', 'allow_comments')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_index(op.f('ix_answer_user_education_id'), table_name='answer')
    op.drop_column('answer', 'user_education_id')
    op.drop_column('answer', 'allow_voting')
    # ### end Alembic commands ###
