"""empty message

Revision ID: 5d7aca4421ff
Revises: edfa2573c56e
Create Date: 2021-01-24 19:18:41.405461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d7aca4421ff'
down_revision = 'edfa2573c56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('answer', 'allow_improvement',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('answer', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('answer', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_bookmark_ibfk_2', 'answer_bookmark', type_='foreignkey')
    op.drop_constraint('answer_bookmark_ibfk_1', 'answer_bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'answer_bookmark', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_bookmark', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_comment_ibfk_2', 'answer_comment', type_='foreignkey')
    op.create_foreign_key(None, 'answer_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_comment_favorite_ibfk_2', 'answer_comment_favorite', type_='foreignkey')
    op.drop_constraint('answer_comment_favorite_ibfk_1', 'answer_comment_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'answer_comment_favorite', 'answer_comment', ['answer_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_comment_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_comment_report_ibfk_1', 'answer_comment_report', type_='foreignkey')
    op.drop_constraint('answer_comment_report_ibfk_2', 'answer_comment_report', type_='foreignkey')
    op.create_foreign_key(None, 'answer_comment_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_comment_report', 'answer_comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_favorite_ibfk_1', 'answer_favorite', type_='foreignkey')
    op.drop_constraint('answer_favorite_ibfk_2', 'answer_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'answer_favorite', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_improvement_ibfk_2', 'answer_improvement', type_='foreignkey')
    op.drop_constraint('answer_improvement_ibfk_1', 'answer_improvement', type_='foreignkey')
    op.create_foreign_key(None, 'answer_improvement', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_improvement', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_improvement_vote_ibfk_2', 'answer_improvement_vote', type_='foreignkey')
    op.drop_constraint('answer_improvement_vote_ibfk_1', 'answer_improvement_vote', type_='foreignkey')
    op.create_foreign_key(None, 'answer_improvement_vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_improvement_vote', 'answer_improvement', ['improvement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_report_ibfk_2', 'answer_report', type_='foreignkey')
    op.drop_constraint('answer_report_ibfk_1', 'answer_report', type_='foreignkey')
    op.create_foreign_key(None, 'answer_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_report', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_share_ibfk_2', 'answer_share', type_='foreignkey')
    op.drop_constraint('answer_share_ibfk_1', 'answer_share', type_='foreignkey')
    op.create_foreign_key(None, 'answer_share', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_share', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('answer_vote_ibfk_1', 'answer_vote', type_='foreignkey')
    op.drop_constraint('answer_vote_ibfk_2', 'answer_vote', type_='foreignkey')
    op.create_foreign_key(None, 'answer_vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_vote', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('article', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('article', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('article_ibfk_1', 'article', type_='foreignkey')
    op.drop_constraint('article_ibfk_2', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_comment_ibfk_2', 'article_comment', type_='foreignkey')
    op.drop_constraint('article_comment_ibfk_1', 'article_comment', type_='foreignkey')
    op.create_foreign_key(None, 'article_comment', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_comment_favorite_ibfk_2', 'article_comment_favorite', type_='foreignkey')
    op.drop_constraint('article_comment_favorite_ibfk_1', 'article_comment_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'article_comment_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_comment_favorite', 'article_comment', ['article_comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_comment_report_ibfk_2', 'article_comment_report', type_='foreignkey')
    op.drop_constraint('article_comment_report_ibfk_1', 'article_comment_report', type_='foreignkey')
    op.create_foreign_key(None, 'article_comment_report', 'article_comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_comment_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_favorite_ibfk_2', 'article_favorite', type_='foreignkey')
    op.drop_constraint('article_favorite_ibfk_1', 'article_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'article_favorite', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_report_ibfk_1', 'article_report', type_='foreignkey')
    op.create_foreign_key(None, 'article_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_share_ibfk_1', 'article_share', type_='foreignkey')
    op.drop_constraint('article_share_ibfk_2', 'article_share', type_='foreignkey')
    op.create_foreign_key(None, 'article_share', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_share', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('article_vote_ibfk_1', 'article_vote', type_='foreignkey')
    op.drop_constraint('article_vote_ibfk_2', 'article_vote', type_='foreignkey')
    op.create_foreign_key(None, 'article_vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_vote', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('post', 'allow_favorite',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('post', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('post', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_comment_ibfk_2', 'post_comment', type_='foreignkey')
    op.drop_constraint('post_comment_ibfk_1', 'post_comment', type_='foreignkey')
    op.create_foreign_key(None, 'post_comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_favorite_ibfk_1', 'post_favorite', type_='foreignkey')
    op.drop_constraint('post_favorite_ibfk_2', 'post_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'post_favorite', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_report_ibfk_1', 'post_report', type_='foreignkey')
    op.create_foreign_key(None, 'post_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_share_ibfk_1', 'post_share', type_='foreignkey')
    op.drop_constraint('post_share_ibfk_2', 'post_share', type_='foreignkey')
    op.create_foreign_key(None, 'post_share', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_share', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_vote_ibfk_1', 'post_vote', type_='foreignkey')
    op.drop_constraint('post_vote_ibfk_2', 'post_vote', type_='foreignkey')
    op.create_foreign_key(None, 'post_vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_vote', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('question', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.drop_constraint('question_ibfk_2', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_bookmark_ibfk_2', 'question_bookmark', type_='foreignkey')
    op.drop_constraint('question_bookmark_ibfk_1', 'question_bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'question_bookmark', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_bookmark', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_comment_ibfk_1', 'question_comment', type_='foreignkey')
    op.drop_constraint('question_comment_ibfk_2', 'question_comment', type_='foreignkey')
    op.create_foreign_key(None, 'question_comment', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_comment_favorite_ibfk_2', 'question_comment_favorite', type_='foreignkey')
    op.drop_constraint('question_comment_favorite_ibfk_1', 'question_comment_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'question_comment_favorite', 'question_comment', ['question_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_comment_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_comment_report_ibfk_1', 'question_comment_report', type_='foreignkey')
    op.drop_constraint('question_comment_report_ibfk_2', 'question_comment_report', type_='foreignkey')
    op.create_foreign_key(None, 'question_comment_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_comment_report', 'question_comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_favorite_ibfk_1', 'question_favorite', type_='foreignkey')
    op.drop_constraint('question_favorite_ibfk_2', 'question_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'question_favorite', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question_proposal', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question_proposal', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question_proposal', 'is_parma_delete',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('question_proposal_ibfk_1', 'question_proposal', type_='foreignkey')
    op.drop_constraint('question_proposal_ibfk_2', 'question_proposal', type_='foreignkey')
    op.create_foreign_key(None, 'question_proposal', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_proposal', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_proposal_topic_ibfk_2', 'question_proposal_topic', type_='foreignkey')
    op.drop_constraint('question_proposal_topic_ibfk_1', 'question_proposal_topic', type_='foreignkey')
    op.create_foreign_key(None, 'question_proposal_topic', 'question_proposal', ['question_proposal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_proposal_topic', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_report_ibfk_2', 'question_report', type_='foreignkey')
    op.drop_constraint('question_report_ibfk_1', 'question_report', type_='foreignkey')
    op.create_foreign_key(None, 'question_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_report', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_share_ibfk_1', 'question_share', type_='foreignkey')
    op.drop_constraint('question_share_ibfk_2', 'question_share', type_='foreignkey')
    op.drop_constraint('question_share_ibfk_3', 'question_share', type_='foreignkey')
    op.create_foreign_key(None, 'question_share', 'user', ['user_shared_to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_share', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_share', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_topic_ibfk_2', 'question_topic', type_='foreignkey')
    op.create_foreign_key(None, 'question_topic', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_user_invite_ibfk_2', 'question_user_invite', type_='foreignkey')
    op.create_foreign_key(None, 'question_user_invite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_vote_ibfk_1', 'question_vote', type_='foreignkey')
    op.drop_constraint('question_vote_ibfk_2', 'question_vote', type_='foreignkey')
    op.create_foreign_key(None, 'question_vote', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reputation_ibfk_2', 'reputation', type_='foreignkey')
    op.drop_constraint('reputation_ibfk_1', 'reputation', type_='foreignkey')
    op.create_foreign_key(None, 'reputation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reputation', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('timeline_ibfk_3', 'timeline', type_='foreignkey')
    op.drop_constraint('timeline_ibfk_2', 'timeline', type_='foreignkey')
    op.drop_constraint('timeline_ibfk_5', 'timeline', type_='foreignkey')
    op.drop_constraint('timeline_ibfk_4', 'timeline', type_='foreignkey')
    op.drop_constraint('timeline_ibfk_7', 'timeline', type_='foreignkey')
    op.drop_constraint('timeline_ibfk_1', 'timeline', type_='foreignkey')
    op.create_foreign_key(None, 'timeline', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'answer_comment', ['answer_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'article_comment', ['article_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'question_comment', ['question_comment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('topic', 'allow_follow',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('topic', 'is_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('topic_ibfk_1', 'topic', type_='foreignkey')
    op.drop_constraint('topic_ibfk_2', 'topic', type_='foreignkey')
    op.create_foreign_key(None, 'topic', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic', 'topic', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_article_ibfk_2', 'topic_article', type_='foreignkey')
    op.drop_constraint('topic_article_ibfk_1', 'topic_article', type_='foreignkey')
    op.create_foreign_key(None, 'topic_article', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_article', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_bookmark_ibfk_1', 'topic_bookmark', type_='foreignkey')
    op.drop_constraint('topic_bookmark_ibfk_2', 'topic_bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'topic_bookmark', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_bookmark', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_follow_ibfk_1', 'topic_follow', type_='foreignkey')
    op.drop_constraint('topic_follow_ibfk_2', 'topic_follow', type_='foreignkey')
    op.create_foreign_key(None, 'topic_follow', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_follow', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_post_ibfk_2', 'topic_post', type_='foreignkey')
    op.drop_constraint('topic_post_ibfk_1', 'topic_post', type_='foreignkey')
    op.create_foreign_key(None, 'topic_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_post', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_report_ibfk_2', 'topic_report', type_='foreignkey')
    op.drop_constraint('topic_report_ibfk_1', 'topic_report', type_='foreignkey')
    op.create_foreign_key(None, 'topic_report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_report', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_share_ibfk_1', 'topic_share', type_='foreignkey')
    op.drop_constraint('topic_share_ibfk_2', 'topic_share', type_='foreignkey')
    op.create_foreign_key(None, 'topic_share', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_share', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_user_endorse_ibfk_1', 'topic_user_endorse', type_='foreignkey')
    op.drop_constraint('topic_user_endorse_ibfk_3', 'topic_user_endorse', type_='foreignkey')
    op.drop_constraint('topic_user_endorse_ibfk_2', 'topic_user_endorse', type_='foreignkey')
    op.create_foreign_key(None, 'topic_user_endorse', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_user_endorse', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_user_endorse', 'user', ['endorsed_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'admin_interaction_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'follow_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'is_birthday_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'is_deactivated',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'my_question_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'my_question_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'show_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint('user_ban_ibfk_1', 'user_ban', type_='foreignkey')
    op.create_foreign_key(None, 'user_ban', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_education_ibfk_1', 'user_education', type_='foreignkey')
    op.create_foreign_key(None, 'user_education', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_follow_ibfk_1', 'user_follow', type_='foreignkey')
    op.drop_constraint('user_follow_ibfk_2', 'user_follow', type_='foreignkey')
    op.create_foreign_key(None, 'user_follow', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_follow', 'user', ['followed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_friend_ibfk_2', 'user_friend', type_='foreignkey')
    op.drop_constraint('user_friend_ibfk_1', 'user_friend', type_='foreignkey')
    op.create_foreign_key(None, 'user_friend', 'user', ['friended_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_friend', 'user', ['friend_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_language_ibfk_1', 'user_language', type_='foreignkey')
    op.drop_constraint('user_language_ibfk_2', 'user_language', type_='foreignkey')
    op.create_foreign_key(None, 'user_language', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_language', 'language', ['language_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_location_ibfk_1', 'user_location', type_='foreignkey')
    op.create_foreign_key(None, 'user_location', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_mailed_article_ibfk_1', 'user_mailed_article', type_='foreignkey')
    op.drop_constraint('user_mailed_article_ibfk_2', 'user_mailed_article', type_='foreignkey')
    op.create_foreign_key(None, 'user_mailed_article', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_mailed_article', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_mailed_question_ibfk_1', 'user_mailed_question', type_='foreignkey')
    op.drop_constraint('user_mailed_question_ibfk_2', 'user_mailed_question', type_='foreignkey')
    op.create_foreign_key(None, 'user_mailed_question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_mailed_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_permission_ibfk_1', 'user_permission', type_='foreignkey')
    op.drop_constraint('user_permission_ibfk_2', 'user_permission', type_='foreignkey')
    op.create_foreign_key(None, 'user_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_permission', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_seen_article_ibfk_2', 'user_seen_article', type_='foreignkey')
    op.drop_constraint('user_seen_article_ibfk_1', 'user_seen_article', type_='foreignkey')
    op.create_foreign_key(None, 'user_seen_article', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_seen_article', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_seen_question_ibfk_1', 'user_seen_question', type_='foreignkey')
    op.drop_constraint('user_seen_question_ibfk_2', 'user_seen_question', type_='foreignkey')
    op.create_foreign_key(None, 'user_seen_question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_seen_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_topic_ibfk_1', 'user_topic', type_='foreignkey')
    op.drop_constraint('user_topic_ibfk_2', 'user_topic', type_='foreignkey')
    op.create_foreign_key(None, 'user_topic', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_topic', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_topic', type_='foreignkey')
    op.drop_constraint(None, 'user_topic', type_='foreignkey')
    op.create_foreign_key('user_topic_ibfk_2', 'user_topic', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_topic_ibfk_1', 'user_topic', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'user_seen_question', type_='foreignkey')
    op.drop_constraint(None, 'user_seen_question', type_='foreignkey')
    op.create_foreign_key('user_seen_question_ibfk_2', 'user_seen_question', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_seen_question_ibfk_1', 'user_seen_question', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'user_seen_article', type_='foreignkey')
    op.drop_constraint(None, 'user_seen_article', type_='foreignkey')
    op.create_foreign_key('user_seen_article_ibfk_1', 'user_seen_article', 'article', ['article_id'], ['id'])
    op.create_foreign_key('user_seen_article_ibfk_2', 'user_seen_article', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.create_foreign_key('user_permission_ibfk_2', 'user_permission', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_permission_ibfk_1', 'user_permission', 'permission', ['permission_id'], ['id'])
    op.drop_constraint(None, 'user_mailed_question', type_='foreignkey')
    op.drop_constraint(None, 'user_mailed_question', type_='foreignkey')
    op.create_foreign_key('user_mailed_question_ibfk_2', 'user_mailed_question', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_mailed_question_ibfk_1', 'user_mailed_question', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'user_mailed_article', type_='foreignkey')
    op.drop_constraint(None, 'user_mailed_article', type_='foreignkey')
    op.create_foreign_key('user_mailed_article_ibfk_2', 'user_mailed_article', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_mailed_article_ibfk_1', 'user_mailed_article', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'user_location', type_='foreignkey')
    op.create_foreign_key('user_location_ibfk_1', 'user_location', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_language', type_='foreignkey')
    op.drop_constraint(None, 'user_language', type_='foreignkey')
    op.create_foreign_key('user_language_ibfk_2', 'user_language', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_language_ibfk_1', 'user_language', 'language', ['language_id'], ['id'])
    op.drop_constraint(None, 'user_friend', type_='foreignkey')
    op.drop_constraint(None, 'user_friend', type_='foreignkey')
    op.create_foreign_key('user_friend_ibfk_1', 'user_friend', 'user', ['friend_id'], ['id'])
    op.create_foreign_key('user_friend_ibfk_2', 'user_friend', 'user', ['friended_id'], ['id'])
    op.drop_constraint(None, 'user_follow', type_='foreignkey')
    op.drop_constraint(None, 'user_follow', type_='foreignkey')
    op.create_foreign_key('user_follow_ibfk_2', 'user_follow', 'user', ['follower_id'], ['id'])
    op.create_foreign_key('user_follow_ibfk_1', 'user_follow', 'user', ['followed_id'], ['id'])
    op.drop_constraint(None, 'user_education', type_='foreignkey')
    op.create_foreign_key('user_education_ibfk_1', 'user_education', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_ban', type_='foreignkey')
    op.create_foreign_key('user_ban_ibfk_1', 'user_ban', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'show_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'my_question_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'my_question_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'is_deactivated',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'is_birthday_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'follow_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_constraint(None, 'topic_user_endorse', type_='foreignkey')
    op.drop_constraint(None, 'topic_user_endorse', type_='foreignkey')
    op.drop_constraint(None, 'topic_user_endorse', type_='foreignkey')
    op.create_foreign_key('topic_user_endorse_ibfk_2', 'topic_user_endorse', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key('topic_user_endorse_ibfk_3', 'topic_user_endorse', 'user', ['user_id'], ['id'])
    op.create_foreign_key('topic_user_endorse_ibfk_1', 'topic_user_endorse', 'user', ['endorsed_id'], ['id'])
    op.drop_constraint(None, 'topic_share', type_='foreignkey')
    op.drop_constraint(None, 'topic_share', type_='foreignkey')
    op.create_foreign_key('topic_share_ibfk_2', 'topic_share', 'user', ['user_id'], ['id'])
    op.create_foreign_key('topic_share_ibfk_1', 'topic_share', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'topic_report', type_='foreignkey')
    op.drop_constraint(None, 'topic_report', type_='foreignkey')
    op.create_foreign_key('topic_report_ibfk_1', 'topic_report', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key('topic_report_ibfk_2', 'topic_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'topic_post', type_='foreignkey')
    op.drop_constraint(None, 'topic_post', type_='foreignkey')
    op.create_foreign_key('topic_post_ibfk_1', 'topic_post', 'post', ['post_id'], ['id'])
    op.create_foreign_key('topic_post_ibfk_2', 'topic_post', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'topic_follow', type_='foreignkey')
    op.drop_constraint(None, 'topic_follow', type_='foreignkey')
    op.create_foreign_key('topic_follow_ibfk_2', 'topic_follow', 'user', ['user_id'], ['id'])
    op.create_foreign_key('topic_follow_ibfk_1', 'topic_follow', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'topic_bookmark', type_='foreignkey')
    op.drop_constraint(None, 'topic_bookmark', type_='foreignkey')
    op.create_foreign_key('topic_bookmark_ibfk_2', 'topic_bookmark', 'user', ['user_id'], ['id'])
    op.create_foreign_key('topic_bookmark_ibfk_1', 'topic_bookmark', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'topic_article', type_='foreignkey')
    op.drop_constraint(None, 'topic_article', type_='foreignkey')
    op.create_foreign_key('topic_article_ibfk_1', 'topic_article', 'article', ['article_id'], ['id'])
    op.create_foreign_key('topic_article_ibfk_2', 'topic_article', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.create_foreign_key('topic_ibfk_2', 'topic', 'user', ['user_id'], ['id'])
    op.create_foreign_key('topic_ibfk_1', 'topic', 'topic', ['parent_id'], ['id'])
    op.alter_column('topic', 'is_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('topic', 'allow_follow',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.create_foreign_key('timeline_ibfk_1', 'timeline', 'answer_comment', ['answer_comment_id'], ['id'])
    op.create_foreign_key('timeline_ibfk_7', 'timeline', 'user', ['user_id'], ['id'])
    op.create_foreign_key('timeline_ibfk_4', 'timeline', 'article', ['article_id'], ['id'])
    op.create_foreign_key('timeline_ibfk_5', 'timeline', 'question_comment', ['question_comment_id'], ['id'])
    op.create_foreign_key('timeline_ibfk_2', 'timeline', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('timeline_ibfk_3', 'timeline', 'article_comment', ['article_comment_id'], ['id'])
    op.drop_constraint(None, 'reputation', type_='foreignkey')
    op.drop_constraint(None, 'reputation', type_='foreignkey')
    op.create_foreign_key('reputation_ibfk_1', 'reputation', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key('reputation_ibfk_2', 'reputation', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'question_vote', type_='foreignkey')
    op.drop_constraint(None, 'question_vote', type_='foreignkey')
    op.create_foreign_key('question_vote_ibfk_2', 'question_vote', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_vote_ibfk_1', 'question_vote', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_user_invite', type_='foreignkey')
    op.create_foreign_key('question_user_invite_ibfk_2', 'question_user_invite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'question_topic', type_='foreignkey')
    op.create_foreign_key('question_topic_ibfk_2', 'question_topic', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'question_share', type_='foreignkey')
    op.drop_constraint(None, 'question_share', type_='foreignkey')
    op.drop_constraint(None, 'question_share', type_='foreignkey')
    op.create_foreign_key('question_share_ibfk_3', 'question_share', 'user', ['user_shared_to_id'], ['id'])
    op.create_foreign_key('question_share_ibfk_2', 'question_share', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_share_ibfk_1', 'question_share', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_report', type_='foreignkey')
    op.drop_constraint(None, 'question_report', type_='foreignkey')
    op.create_foreign_key('question_report_ibfk_1', 'question_report', 'question', ['question_id'], ['id'])
    op.create_foreign_key('question_report_ibfk_2', 'question_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'question_proposal_topic', type_='foreignkey')
    op.drop_constraint(None, 'question_proposal_topic', type_='foreignkey')
    op.create_foreign_key('question_proposal_topic_ibfk_1', 'question_proposal_topic', 'question_proposal', ['question_proposal_id'], ['id'])
    op.create_foreign_key('question_proposal_topic_ibfk_2', 'question_proposal_topic', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(None, 'question_proposal', type_='foreignkey')
    op.drop_constraint(None, 'question_proposal', type_='foreignkey')
    op.create_foreign_key('question_proposal_ibfk_2', 'question_proposal', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_proposal_ibfk_1', 'question_proposal', 'topic', ['fixed_topic_id'], ['id'])
    op.alter_column('question_proposal', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_parma_delete',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('question_proposal', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('question_proposal', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_constraint(None, 'question_favorite', type_='foreignkey')
    op.drop_constraint(None, 'question_favorite', type_='foreignkey')
    op.create_foreign_key('question_favorite_ibfk_2', 'question_favorite', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_favorite_ibfk_1', 'question_favorite', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_comment_report', type_='foreignkey')
    op.drop_constraint(None, 'question_comment_report', type_='foreignkey')
    op.create_foreign_key('question_comment_report_ibfk_2', 'question_comment_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_comment_report_ibfk_1', 'question_comment_report', 'question_comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'question_comment_favorite', type_='foreignkey')
    op.drop_constraint(None, 'question_comment_favorite', type_='foreignkey')
    op.create_foreign_key('question_comment_favorite_ibfk_1', 'question_comment_favorite', 'question_comment', ['question_comment_id'], ['id'])
    op.create_foreign_key('question_comment_favorite_ibfk_2', 'question_comment_favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'question_comment', type_='foreignkey')
    op.drop_constraint(None, 'question_comment', type_='foreignkey')
    op.create_foreign_key('question_comment_ibfk_2', 'question_comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_comment_ibfk_1', 'question_comment', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'question_bookmark', type_='foreignkey')
    op.drop_constraint(None, 'question_bookmark', type_='foreignkey')
    op.create_foreign_key('question_bookmark_ibfk_1', 'question_bookmark', 'question', ['question_id'], ['id'])
    op.create_foreign_key('question_bookmark_ibfk_2', 'question_bookmark', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_2', 'question', 'user', ['user_id'], ['id'])
    op.create_foreign_key('question_ibfk_1', 'question', 'topic', ['fixed_topic_id'], ['id'])
    op.alter_column('question', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('question', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('question', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('question', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_constraint(None, 'post_vote', type_='foreignkey')
    op.drop_constraint(None, 'post_vote', type_='foreignkey')
    op.create_foreign_key('post_vote_ibfk_2', 'post_vote', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_vote_ibfk_1', 'post_vote', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_share', type_='foreignkey')
    op.drop_constraint(None, 'post_share', type_='foreignkey')
    op.create_foreign_key('post_share_ibfk_2', 'post_share', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_share_ibfk_1', 'post_share', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_report', type_='foreignkey')
    op.create_foreign_key('post_report_ibfk_1', 'post_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'post_favorite', type_='foreignkey')
    op.drop_constraint(None, 'post_favorite', type_='foreignkey')
    op.create_foreign_key('post_favorite_ibfk_2', 'post_favorite', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_favorite_ibfk_1', 'post_favorite', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.create_foreign_key('post_comment_ibfk_1', 'post_comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key('post_comment_ibfk_2', 'post_comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_2', 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_ibfk_1', 'post', 'topic', ['fixed_topic_id'], ['id'])
    op.alter_column('post', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('post', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('post', 'allow_favorite',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_constraint(None, 'article_vote', type_='foreignkey')
    op.drop_constraint(None, 'article_vote', type_='foreignkey')
    op.create_foreign_key('article_vote_ibfk_2', 'article_vote', 'user', ['user_id'], ['id'])
    op.create_foreign_key('article_vote_ibfk_1', 'article_vote', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'article_share', type_='foreignkey')
    op.drop_constraint(None, 'article_share', type_='foreignkey')
    op.create_foreign_key('article_share_ibfk_2', 'article_share', 'user', ['user_id'], ['id'])
    op.create_foreign_key('article_share_ibfk_1', 'article_share', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'article_report', type_='foreignkey')
    op.create_foreign_key('article_report_ibfk_1', 'article_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'article_favorite', type_='foreignkey')
    op.drop_constraint(None, 'article_favorite', type_='foreignkey')
    op.create_foreign_key('article_favorite_ibfk_1', 'article_favorite', 'article', ['article_id'], ['id'])
    op.create_foreign_key('article_favorite_ibfk_2', 'article_favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'article_comment_report', type_='foreignkey')
    op.drop_constraint(None, 'article_comment_report', type_='foreignkey')
    op.create_foreign_key('article_comment_report_ibfk_1', 'article_comment_report', 'article_comment', ['comment_id'], ['id'])
    op.create_foreign_key('article_comment_report_ibfk_2', 'article_comment_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'article_comment_favorite', type_='foreignkey')
    op.drop_constraint(None, 'article_comment_favorite', type_='foreignkey')
    op.create_foreign_key('article_comment_favorite_ibfk_1', 'article_comment_favorite', 'article_comment', ['article_comment_id'], ['id'])
    op.create_foreign_key('article_comment_favorite_ibfk_2', 'article_comment_favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'article_comment', type_='foreignkey')
    op.drop_constraint(None, 'article_comment', type_='foreignkey')
    op.create_foreign_key('article_comment_ibfk_1', 'article_comment', 'article', ['article_id'], ['id'])
    op.create_foreign_key('article_comment_ibfk_2', 'article_comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_ibfk_2', 'article', 'user', ['user_id'], ['id'])
    op.create_foreign_key('article_ibfk_1', 'article', 'topic', ['fixed_topic_id'], ['id'])
    op.alter_column('article', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('article', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_constraint(None, 'answer_vote', type_='foreignkey')
    op.drop_constraint(None, 'answer_vote', type_='foreignkey')
    op.create_foreign_key('answer_vote_ibfk_2', 'answer_vote', 'user', ['user_id'], ['id'])
    op.create_foreign_key('answer_vote_ibfk_1', 'answer_vote', 'answer', ['answer_id'], ['id'])
    op.drop_constraint(None, 'answer_share', type_='foreignkey')
    op.drop_constraint(None, 'answer_share', type_='foreignkey')
    op.create_foreign_key('answer_share_ibfk_1', 'answer_share', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('answer_share_ibfk_2', 'answer_share', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_report', type_='foreignkey')
    op.drop_constraint(None, 'answer_report', type_='foreignkey')
    op.create_foreign_key('answer_report_ibfk_1', 'answer_report', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('answer_report_ibfk_2', 'answer_report', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_improvement_vote', type_='foreignkey')
    op.drop_constraint(None, 'answer_improvement_vote', type_='foreignkey')
    op.create_foreign_key('answer_improvement_vote_ibfk_1', 'answer_improvement_vote', 'answer_improvement', ['improvement_id'], ['id'])
    op.create_foreign_key('answer_improvement_vote_ibfk_2', 'answer_improvement_vote', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_improvement', type_='foreignkey')
    op.drop_constraint(None, 'answer_improvement', type_='foreignkey')
    op.create_foreign_key('answer_improvement_ibfk_1', 'answer_improvement', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('answer_improvement_ibfk_2', 'answer_improvement', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_favorite', type_='foreignkey')
    op.drop_constraint(None, 'answer_favorite', type_='foreignkey')
    op.create_foreign_key('answer_favorite_ibfk_2', 'answer_favorite', 'user', ['user_id'], ['id'])
    op.create_foreign_key('answer_favorite_ibfk_1', 'answer_favorite', 'answer', ['answer_id'], ['id'])
    op.drop_constraint(None, 'answer_comment_report', type_='foreignkey')
    op.drop_constraint(None, 'answer_comment_report', type_='foreignkey')
    op.create_foreign_key('answer_comment_report_ibfk_2', 'answer_comment_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key('answer_comment_report_ibfk_1', 'answer_comment_report', 'answer_comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'answer_comment_favorite', type_='foreignkey')
    op.drop_constraint(None, 'answer_comment_favorite', type_='foreignkey')
    op.create_foreign_key('answer_comment_favorite_ibfk_1', 'answer_comment_favorite', 'answer_comment', ['answer_comment_id'], ['id'])
    op.create_foreign_key('answer_comment_favorite_ibfk_2', 'answer_comment_favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_comment', type_='foreignkey')
    op.create_foreign_key('answer_comment_ibfk_2', 'answer_comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer_bookmark', type_='foreignkey')
    op.drop_constraint(None, 'answer_bookmark', type_='foreignkey')
    op.create_foreign_key('answer_bookmark_ibfk_1', 'answer_bookmark', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('answer_bookmark_ibfk_2', 'answer_bookmark', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_2', 'answer', 'user', ['user_id'], ['id'])
    op.create_foreign_key('answer_ibfk_1', 'answer', 'question', ['question_id'], ['id'])
    op.alter_column('answer', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('answer', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('answer', 'allow_improvement',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('answer', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    # ### end Alembic commands ###
