"""rename owner_user_id to user_id

Revision ID: 61cb61da2cf8
Revises: 1dcff21a69fd
Create Date: 2021-04-14 20:54:01.326198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61cb61da2cf8'
down_revision = '1dcff21a69fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('poll', sa.Column('fixed_topic_id', sa.Integer(), nullable=False))
    #op.add_column('poll', sa.Column('user_id', sa.Integer(), nullable=False))
    #op.create_index(op.f('ix_poll_user_id'), 'poll', ['user_id'], unique=False)
    #op.drop_constraint('poll_ibfk_1', 'poll', type_='foreignkey')
    #op.drop_index('ix_poll_owner_user_id', table_name='poll')
    #op.create_foreign_key(None, 'poll', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    #op.create_foreign_key(None, 'poll', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    #op.drop_column('poll', 'owner_user_id')
    op.add_column('user_education', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_employment', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_language', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_location', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_topic', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic', 'is_visible')
    op.drop_column('user_location', 'is_visible')
    op.drop_column('user_language', 'is_visible')
    op.drop_column('user_employment', 'is_visible')
    op.drop_column('user_education', 'is_visible')
    op.add_column('poll', sa.Column('owner_user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_constraint(None, 'poll', type_='foreignkey')
    #op.create_foreign_key('poll_ibfk_1', 'poll', 'user', ['owner_user_id'], ['id'], ondelete='CASCADE')
    #op.create_index('ix_poll_owner_user_id', 'poll', ['owner_user_id'], unique=False)
    #op.drop_index(op.f('ix_poll_user_id'), table_name='poll')
    #op.drop_column('poll', 'user_id')
    #op.drop_column('poll', 'fixed_topic_id')
    # ### end Alembic commands ###
