"""empty message

Revision ID: 65234ab59a37
Revises: 
Create Date: 2020-08-10 17:02:30.463777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65234ab59a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_question',
    sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('topic_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fixed_topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fixed_topic_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('question', mysql.TEXT(), nullable=True),
    sa.Column('markdown', mysql.TEXT(), nullable=True),
    sa.Column('html', mysql.TEXT(), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('views_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_activity', mysql.DATETIME(), nullable=True),
    sa.Column('answers_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accepted_answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('anonymous', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('image_ids', mysql.JSON(), nullable=True),
    sa.Column('upvote_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('downvote_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('share_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('favorite_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
