"""empty message

Revision ID: 72b97a4053ce
Revises: 
Create Date: 2020-08-08 17:39:41.943024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b97a4053ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.UnicodeText(), nullable=True),
    sa.Column('markdown', sa.UnicodeText(), nullable=True),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('image_ids', sa.JSON(), nullable=True),
    sa.Column('user_hidden', sa.Boolean(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorited_user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=True),
    sa.Column('fixed_topic_name', sa.String(), nullable=True),
    sa.Column('question', sa.UnicodeText(), nullable=True),
    sa.Column('markdown', sa.UnicodeText(), nullable=True),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('answers_count', sa.Integer(), nullable=True),
    sa.Column('accepted_answer_id', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('user_hidden', sa.Boolean(), nullable=True),
    sa.Column('image_ids', sa.JSON(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('new_password_hash', sa.String(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('required_time', sa.Time(), nullable=True),
    sa.Column('recovery_code', sa.String(), nullable=True),
    sa.Column('code_created_date', sa.Date(), nullable=True),
    sa.Column('code_created_time', sa.Time(), nullable=True),
    sa.Column('code_duration_time', sa.Float(), nullable=True),
    sa.Column('code_sent_date', sa.Date(), nullable=True),
    sa.Column('code_sent_time', sa.Time(), nullable=True),
    sa.Column('trial_number', sa.Integer(), nullable=True),
    sa.Column('continued', sa.Boolean(), nullable=True),
    sa.Column('session_start_date', sa.Date(), nullable=True),
    sa.Column('session_start_time', sa.Time(), nullable=True),
    sa.Column('session_duration', sa.Float(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('inappropriate', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('registered_time', sa.Time(), nullable=True),
    sa.Column('activation_code', sa.String(), nullable=True),
    sa.Column('code_created_date', sa.Date(), nullable=True),
    sa.Column('code_created_time', sa.Time(), nullable=True),
    sa.Column('code_duration_time', sa.Float(), nullable=True),
    sa.Column('code_sent_date', sa.Date(), nullable=True),
    sa.Column('code_sent_time', sa.Time(), nullable=True),
    sa.Column('trial_number', sa.Integer(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_question',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=True),
    sa.Column('fixed_topic_name', sa.String(), nullable=True),
    sa.Column('question', sa.UnicodeText(), nullable=True),
    sa.Column('markdown', sa.UnicodeText(), nullable=True),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('answers_count', sa.Integer(), nullable=True),
    sa.Column('accepted_answer_id', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('user_hidden', sa.Boolean(), nullable=True),
    sa.Column('image_ids', sa.JSON(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('verification_sms_time', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('profile_pic_data_url', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('profile_views', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('about_me_markdown', sa.Text(), nullable=True),
    sa.Column('about_me_html', sa.Text(), nullable=True),
    sa.Column('people_reached', sa.Integer(), nullable=True),
    sa.Column('show_email_publicly_setting', sa.Boolean(), nullable=True),
    sa.Column('hoovada_digests_setting', sa.Boolean(), nullable=True),
    sa.Column('hoovada_digests_frequency_setting', sa.String(), nullable=True),
    sa.Column('questions_you_asked_or_followed_setting', sa.Boolean(), nullable=True),
    sa.Column('questions_you_asked_or_followed_frequency_setting', sa.String(), nullable=True),
    sa.Column('people_you_follow_setting', sa.Boolean(), nullable=True),
    sa.Column('people_you_follow_frequency_setting', sa.String(), nullable=True),
    sa.Column('email_stories_topics_setting', sa.Boolean(), nullable=True),
    sa.Column('email_stories_topics_frequency_setting', sa.String(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('question_favorite_count', sa.Integer(), nullable=True),
    sa.Column('question_favorited_count', sa.Integer(), nullable=True),
    sa.Column('question_share_count', sa.Integer(), nullable=True),
    sa.Column('question_shared_count', sa.Integer(), nullable=True),
    sa.Column('question_report_count', sa.Integer(), nullable=True),
    sa.Column('question_reported_count', sa.Integer(), nullable=True),
    sa.Column('question_upvote_count', sa.Integer(), nullable=True),
    sa.Column('question_upvoted_count', sa.Integer(), nullable=True),
    sa.Column('question_downvote_count', sa.Integer(), nullable=True),
    sa.Column('question_downvoted_count', sa.Integer(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=True),
    sa.Column('answer_share_count', sa.Integer(), nullable=True),
    sa.Column('answer_shared_count', sa.Integer(), nullable=True),
    sa.Column('answer_favorite_count', sa.Integer(), nullable=True),
    sa.Column('answer_favorited_count', sa.Integer(), nullable=True),
    sa.Column('answer_upvote_count', sa.Integer(), nullable=True),
    sa.Column('answer_upvoted_count', sa.Integer(), nullable=True),
    sa.Column('answer_downvote_count', sa.Integer(), nullable=True),
    sa.Column('answer_downvoted_count', sa.Integer(), nullable=True),
    sa.Column('answer_report_count', sa.Integer(), nullable=True),
    sa.Column('answer_reported_count', sa.Integer(), nullable=True),
    sa.Column('topic_follow_count', sa.Integer(), nullable=True),
    sa.Column('topic_followed_count', sa.Integer(), nullable=True),
    sa.Column('topic_created_count', sa.Integer(), nullable=True),
    sa.Column('user_follow_count', sa.Integer(), nullable=True),
    sa.Column('user_followed_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('comment_upvote_count', sa.Integer(), nullable=True),
    sa.Column('comment_upvoted_count', sa.Integer(), nullable=True),
    sa.Column('comment_downvote_count', sa.Integer(), nullable=True),
    sa.Column('comment_downvoted_count', sa.Integer(), nullable=True),
    sa.Column('comment_report_count', sa.Integer(), nullable=True),
    sa.Column('comment_reported_count', sa.Integer(), nullable=True),
    sa.Column('user_report_count', sa.Integer(), nullable=True),
    sa.Column('user_reported_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_currently_work', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('up_vote', sa.Boolean(), nullable=True),
    sa.Column('down_vote', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('user_topic')
    op.drop_table('user_employment')
    op.drop_table('user')
    op.drop_table('topic_question')
    op.drop_table('topic')
    op.drop_table('social_account')
    op.drop_table('signup_user')
    op.drop_table('share')
    op.drop_table('reputation')
    op.drop_table('report')
    op.drop_table('recovery_user')
    op.drop_table('question_topic')
    op.drop_table('question')
    op.drop_table('favorite')
    op.drop_table('comment')
    op.drop_table('blacklist_tokens')
    op.drop_table('answer')
    # ### end Alembic commands ###
