"""add related tables poll

Revision ID: 79cf9c8fc152
Revises: 1c9462012bcd
Create Date: 2021-04-10 15:52:46.371800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cf9c8fc152'
down_revision = '1c9462012bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_report_poll_id'), 'poll_report', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_report_user_id'), 'poll_report', ['user_id'], unique=False)
    op.create_table('poll_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_bookmark_user_id'), 'poll_bookmark', ['user_id'], unique=False)
    op.create_table('poll_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_poll_id'), 'poll_comment', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_user_id'), 'poll_comment', ['user_id'], unique=False)
    op.create_table('poll_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_favorite_user_id'), 'poll_favorite', ['user_id'], unique=False)
    op.create_table('poll_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_share_poll_id'), 'poll_share', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_share_user_id'), 'poll_share', ['user_id'], unique=False)
    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_vote_poll_id'), 'poll_vote', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_vote_user_id'), 'poll_vote', ['user_id'], unique=False)
    op.create_table('poll_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_favorite_user_id'), 'poll_comment_favorite', ['user_id'], unique=False)
    op.create_table('poll_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_report_comment_id'), 'poll_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_report_user_id'), 'poll_comment_report', ['user_id'], unique=False)
    op.add_column('poll', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('poll', sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('poll', sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('poll', sa.Column('share_count', sa.Integer(), nullable=True))
    op.add_column('poll', sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'upvote_count')
    op.drop_column('poll', 'share_count')
    op.drop_column('poll', 'favorite_count')
    op.drop_column('poll', 'downvote_count')
    op.drop_column('poll', 'comment_count')
    op.drop_index(op.f('ix_poll_comment_report_user_id'), table_name='poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_report_comment_id'), table_name='poll_comment_report')
    op.drop_table('poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_favorite_user_id'), table_name='poll_comment_favorite')
    op.drop_table('poll_comment_favorite')
    op.drop_index(op.f('ix_poll_vote_user_id'), table_name='poll_vote')
    op.drop_index(op.f('ix_poll_vote_poll_id'), table_name='poll_vote')
    op.drop_table('poll_vote')
    op.drop_index(op.f('ix_poll_share_user_id'), table_name='poll_share')
    op.drop_index(op.f('ix_poll_share_poll_id'), table_name='poll_share')
    op.drop_table('poll_share')
    op.drop_index(op.f('ix_poll_favorite_user_id'), table_name='poll_favorite')
    op.drop_table('poll_favorite')
    op.drop_index(op.f('ix_poll_comment_user_id'), table_name='poll_comment')
    op.drop_index(op.f('ix_poll_comment_poll_id'), table_name='poll_comment')
    op.drop_table('poll_comment')
    op.drop_index(op.f('ix_poll_bookmark_user_id'), table_name='poll_bookmark')
    op.drop_table('poll_bookmark')
    op.drop_index(op.f('ix_poll_report_user_id'), table_name='poll_report')
    op.drop_index(op.f('ix_poll_report_poll_id'), table_name='poll_report')
    op.drop_table('poll_report')
    # ### end Alembic commands ###
