"""create autoincrement for question_user_invite

Revision ID: 853626c2595a
Revises: 4db95e3af3de
Create Date: 2021-04-07 15:32:04.150190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853626c2595a'
down_revision = '4db95e3af3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_user_invite', sa.Column('id', sa.Integer(), nullable=False))
    op.execute("ALTER TABLE hoovada.`question_user_invite` ADD INDEX(`id`)")
    op.execute("ALTER TABLE hoovada.`question_user_invite` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_user_invite', 'id')
    # ### end Alembic commands ###
