"""empty message

Revision ID: 8ddcb63384d6
Revises: a09f73768810
Create Date: 2021-01-11 22:35:10.148723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ddcb63384d6'
down_revision = 'a09f73768810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('answer', 'allow_improvement',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('answer', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('answer', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_bookmark_user_id'), 'answer_bookmark', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_user_id'), 'answer_comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_favorite_user_id'), 'answer_comment_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_report_comment_id'), 'answer_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_report_user_id'), 'answer_comment_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_favorite_user_id'), 'answer_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_answer_id'), 'answer_improvement', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_user_id'), 'answer_improvement', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_vote_improvement_id'), 'answer_improvement_vote', ['improvement_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_vote_user_id'), 'answer_improvement_vote', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_report_answer_id'), 'answer_report', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_report_user_id'), 'answer_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_share_answer_id'), 'answer_share', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_share_user_id'), 'answer_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_vote_answer_id'), 'answer_vote', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_vote_user_id'), 'answer_vote', ['user_id'], unique=False)
    op.alter_column('article', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('article', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_article_fixed_topic_id'), 'article', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_article_user_id'), 'article', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_comment_user_id'), 'article_comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_comment_favorite_user_id'), 'article_comment_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_comment_report_comment_id'), 'article_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_article_comment_report_user_id'), 'article_comment_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_favorite_user_id'), 'article_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_report_article_id'), 'article_report', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_report_user_id'), 'article_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_share_article_id'), 'article_share', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_share_user_id'), 'article_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_vote_article_id'), 'article_vote', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_vote_user_id'), 'article_vote', ['user_id'], unique=False)
    op.alter_column('post', 'allow_favorite',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('post', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('post', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_post_fixed_topic_id'), 'post', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_comment_user_id'), 'post_comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_favorite_user_id'), 'post_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_report_post_id'), 'post_report', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_report_user_id'), 'post_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_share_post_id'), 'post_share', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_share_user_id'), 'post_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_vote_post_id'), 'post_vote', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_vote_user_id'), 'post_vote', ['user_id'], unique=False)
    op.alter_column('question', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('question', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_question_fixed_topic_id'), 'question', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_question_user_id'), 'question', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_bookmark_user_id'), 'question_bookmark', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_comment_user_id'), 'question_comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_comment_favorite_user_id'), 'question_comment_favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_comment_report_comment_id'), 'question_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_question_comment_report_user_id'), 'question_comment_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_favorite_user_id'), 'question_favorite', ['user_id'], unique=False)
    op.alter_column('question_proposal', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_parma_delete',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_question_proposal_fixed_topic_id'), 'question_proposal', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_question_proposal_question_id'), 'question_proposal', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_proposal_user_id'), 'question_proposal', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_report_question_id'), 'question_report', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_report_user_id'), 'question_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_share_question_id'), 'question_share', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_share_user_id'), 'question_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_share_user_shared_to_id'), 'question_share', ['user_shared_to_id'], unique=False)
    op.create_index(op.f('ix_question_vote_question_id'), 'question_vote', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_vote_user_id'), 'question_vote', ['user_id'], unique=False)
    op.create_index(op.f('ix_reputation_topic_id'), 'reputation', ['topic_id'], unique=False)
    op.create_index(op.f('ix_reputation_user_id'), 'reputation', ['user_id'], unique=False)
    op.create_index(op.f('ix_social_account_user_id'), 'social_account', ['user_id'], unique=False)
    op.create_index(op.f('ix_timeline_answer_id'), 'timeline', ['answer_id'], unique=False)
    op.create_index(op.f('ix_timeline_article_id'), 'timeline', ['article_id'], unique=False)
    op.create_index(op.f('ix_timeline_question_id'), 'timeline', ['question_id'], unique=False)
    op.create_index(op.f('ix_timeline_user_id'), 'timeline', ['user_id'], unique=False)
    op.alter_column('topic', 'allow_follow',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('topic', 'is_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_topic_parent_id'), 'topic', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topic_user_id'), 'topic', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_bookmark_user_id'), 'topic_bookmark', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_follow_topic_id'), 'topic_follow', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_follow_user_id'), 'topic_follow', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_report_topic_id'), 'topic_report', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_report_user_id'), 'topic_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_share_topic_id'), 'topic_share', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_share_user_id'), 'topic_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_user_endorse_endorsed_id'), 'topic_user_endorse', ['endorsed_id'], unique=False)
    op.create_index(op.f('ix_topic_user_endorse_topic_id'), 'topic_user_endorse', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_user_endorse_user_id'), 'topic_user_endorse', ['user_id'], unique=False)
    op.alter_column('user', 'admin_interaction_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'follow_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'is_birthday_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'is_deactivated',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user', 'my_question_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'my_question_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user', 'show_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    op.drop_index('display_name', table_name='user')
    op.create_index(op.f('ix_user_education_user_id'), 'user_education', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_employment_user_id'), 'user_employment', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_follow_followed_id'), 'user_follow', ['followed_id'], unique=False)
    op.create_index(op.f('ix_user_follow_follower_id'), 'user_follow', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_friend_friend_id'), 'user_friend', ['friend_id'], unique=False)
    op.create_index(op.f('ix_user_friend_friended_id'), 'user_friend', ['friended_id'], unique=False)
    op.create_index(op.f('ix_user_language_language_id'), 'user_language', ['language_id'], unique=False)
    op.create_index(op.f('ix_user_language_user_id'), 'user_language', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_location_user_id'), 'user_location', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_article_article_id'), 'user_mailed_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_article_user_id'), 'user_mailed_article', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_question_question_id'), 'user_mailed_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_question_user_id'), 'user_mailed_question', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_seen_article_article_id'), 'user_seen_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_seen_article_user_id'), 'user_seen_article', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_seen_question_question_id'), 'user_seen_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_seen_question_user_id'), 'user_seen_question', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_topic_topic_id'), 'user_topic', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_user_id'), 'user_topic', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_topic_user_id'), table_name='user_topic')
    op.drop_index(op.f('ix_user_topic_topic_id'), table_name='user_topic')
    op.drop_index(op.f('ix_user_seen_question_user_id'), table_name='user_seen_question')
    op.drop_index(op.f('ix_user_seen_question_question_id'), table_name='user_seen_question')
    op.drop_index(op.f('ix_user_seen_article_user_id'), table_name='user_seen_article')
    op.drop_index(op.f('ix_user_seen_article_article_id'), table_name='user_seen_article')
    op.drop_index(op.f('ix_user_mailed_question_user_id'), table_name='user_mailed_question')
    op.drop_index(op.f('ix_user_mailed_question_question_id'), table_name='user_mailed_question')
    op.drop_index(op.f('ix_user_mailed_article_user_id'), table_name='user_mailed_article')
    op.drop_index(op.f('ix_user_mailed_article_article_id'), table_name='user_mailed_article')
    op.drop_index(op.f('ix_user_location_user_id'), table_name='user_location')
    op.drop_index(op.f('ix_user_language_user_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_language_language_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_friend_friended_id'), table_name='user_friend')
    op.drop_index(op.f('ix_user_friend_friend_id'), table_name='user_friend')
    op.drop_index(op.f('ix_user_follow_follower_id'), table_name='user_follow')
    op.drop_index(op.f('ix_user_follow_followed_id'), table_name='user_follow')
    op.drop_index(op.f('ix_user_employment_user_id'), table_name='user_employment')
    op.drop_index(op.f('ix_user_education_user_id'), table_name='user_education')
    op.create_index('display_name', 'user', ['display_name'], unique=True)
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.alter_column('user', 'show_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'question_invite_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'my_question_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'my_question_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'is_deactivated',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'is_birthday_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'friend_request_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'follow_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_notify_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('user', 'admin_interaction_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_topic_user_endorse_user_id'), table_name='topic_user_endorse')
    op.drop_index(op.f('ix_topic_user_endorse_topic_id'), table_name='topic_user_endorse')
    op.drop_index(op.f('ix_topic_user_endorse_endorsed_id'), table_name='topic_user_endorse')
    op.drop_index(op.f('ix_topic_share_user_id'), table_name='topic_share')
    op.drop_index(op.f('ix_topic_share_topic_id'), table_name='topic_share')
    op.drop_index(op.f('ix_topic_report_user_id'), table_name='topic_report')
    op.drop_index(op.f('ix_topic_report_topic_id'), table_name='topic_report')
    op.drop_index(op.f('ix_topic_follow_user_id'), table_name='topic_follow')
    op.drop_index(op.f('ix_topic_follow_topic_id'), table_name='topic_follow')
    op.drop_index(op.f('ix_topic_bookmark_user_id'), table_name='topic_bookmark')
    op.drop_index(op.f('ix_topic_user_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_parent_id'), table_name='topic')
    op.alter_column('topic', 'is_nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('topic', 'allow_follow',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_timeline_user_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_question_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_article_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_answer_id'), table_name='timeline')
    op.drop_index(op.f('ix_social_account_user_id'), table_name='social_account')
    op.drop_index(op.f('ix_reputation_user_id'), table_name='reputation')
    op.drop_index(op.f('ix_reputation_topic_id'), table_name='reputation')
    op.drop_index(op.f('ix_question_vote_user_id'), table_name='question_vote')
    op.drop_index(op.f('ix_question_vote_question_id'), table_name='question_vote')
    op.drop_index(op.f('ix_question_share_user_shared_to_id'), table_name='question_share')
    op.drop_index(op.f('ix_question_share_user_id'), table_name='question_share')
    op.drop_index(op.f('ix_question_share_question_id'), table_name='question_share')
    op.drop_index(op.f('ix_question_report_user_id'), table_name='question_report')
    op.drop_index(op.f('ix_question_report_question_id'), table_name='question_report')
    op.drop_index(op.f('ix_question_proposal_user_id'), table_name='question_proposal')
    op.drop_index(op.f('ix_question_proposal_question_id'), table_name='question_proposal')
    op.drop_index(op.f('ix_question_proposal_fixed_topic_id'), table_name='question_proposal')
    op.alter_column('question_proposal', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_parma_delete',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('question_proposal', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_question_favorite_user_id'), table_name='question_favorite')
    op.drop_index(op.f('ix_question_comment_report_user_id'), table_name='question_comment_report')
    op.drop_index(op.f('ix_question_comment_report_comment_id'), table_name='question_comment_report')
    op.drop_index(op.f('ix_question_comment_favorite_user_id'), table_name='question_comment_favorite')
    op.drop_index(op.f('ix_question_comment_user_id'), table_name='question_comment')
    op.drop_index(op.f('ix_question_bookmark_user_id'), table_name='question_bookmark')
    op.drop_index(op.f('ix_question_user_id'), table_name='question')
    op.drop_index(op.f('ix_question_fixed_topic_id'), table_name='question')
    op.alter_column('question', 'is_private',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'allow_video_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('question', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('question', 'allow_audio_answer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_post_vote_user_id'), table_name='post_vote')
    op.drop_index(op.f('ix_post_vote_post_id'), table_name='post_vote')
    op.drop_index(op.f('ix_post_share_user_id'), table_name='post_share')
    op.drop_index(op.f('ix_post_share_post_id'), table_name='post_share')
    op.drop_index(op.f('ix_post_report_user_id'), table_name='post_report')
    op.drop_index(op.f('ix_post_report_post_id'), table_name='post_report')
    op.drop_index(op.f('ix_post_favorite_user_id'), table_name='post_favorite')
    op.drop_index(op.f('ix_post_comment_user_id'), table_name='post_comment')
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_index(op.f('ix_post_fixed_topic_id'), table_name='post')
    op.alter_column('post', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('post', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('post', 'allow_favorite',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_article_vote_user_id'), table_name='article_vote')
    op.drop_index(op.f('ix_article_vote_article_id'), table_name='article_vote')
    op.drop_index(op.f('ix_article_share_user_id'), table_name='article_share')
    op.drop_index(op.f('ix_article_share_article_id'), table_name='article_share')
    op.drop_index(op.f('ix_article_report_user_id'), table_name='article_report')
    op.drop_index(op.f('ix_article_report_article_id'), table_name='article_report')
    op.drop_index(op.f('ix_article_favorite_user_id'), table_name='article_favorite')
    op.drop_index(op.f('ix_article_comment_report_user_id'), table_name='article_comment_report')
    op.drop_index(op.f('ix_article_comment_report_comment_id'), table_name='article_comment_report')
    op.drop_index(op.f('ix_article_comment_favorite_user_id'), table_name='article_comment_favorite')
    op.drop_index(op.f('ix_article_comment_user_id'), table_name='article_comment')
    op.drop_index(op.f('ix_article_user_id'), table_name='article')
    op.drop_index(op.f('ix_article_fixed_topic_id'), table_name='article')
    op.alter_column('article', 'is_draft',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('article', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_answer_vote_user_id'), table_name='answer_vote')
    op.drop_index(op.f('ix_answer_vote_answer_id'), table_name='answer_vote')
    op.drop_index(op.f('ix_answer_share_user_id'), table_name='answer_share')
    op.drop_index(op.f('ix_answer_share_answer_id'), table_name='answer_share')
    op.drop_index(op.f('ix_answer_report_user_id'), table_name='answer_report')
    op.drop_index(op.f('ix_answer_report_answer_id'), table_name='answer_report')
    op.drop_index(op.f('ix_answer_improvement_vote_user_id'), table_name='answer_improvement_vote')
    op.drop_index(op.f('ix_answer_improvement_vote_improvement_id'), table_name='answer_improvement_vote')
    op.drop_index(op.f('ix_answer_improvement_user_id'), table_name='answer_improvement')
    op.drop_index(op.f('ix_answer_improvement_answer_id'), table_name='answer_improvement')
    op.drop_index(op.f('ix_answer_favorite_user_id'), table_name='answer_favorite')
    op.drop_index(op.f('ix_answer_comment_report_user_id'), table_name='answer_comment_report')
    op.drop_index(op.f('ix_answer_comment_report_comment_id'), table_name='answer_comment_report')
    op.drop_index(op.f('ix_answer_comment_favorite_user_id'), table_name='answer_comment_favorite')
    op.drop_index(op.f('ix_answer_comment_user_id'), table_name='answer_comment')
    op.drop_index(op.f('ix_answer_bookmark_user_id'), table_name='answer_bookmark')
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.alter_column('answer', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('answer', 'is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('answer', 'allow_improvement',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('answer', 'allow_comments',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    # ### end Alembic commands ###
