"""create new column is_first_log_in in table user and status in table question_user_invite

Revision ID: 9f93f812e0fd
Revises: 6a59e4d9d41c
Create Date: 2021-03-13 23:51:51.814655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f93f812e0fd'
down_revision = '6a59e4d9d41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_user_invite', sa.Column('status', sa.SmallInteger(), nullable=True, comment='Determine the status of the invited question (0: unanswered, 1: answered, 2: declined)'))
    op.add_column('user', sa.Column('is_first_log_in', sa.SmallInteger(), server_default='0', nullable=True, comment='Determine if this is the first time user logged in (0: No, 1: Yes)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_first_log_in')
    op.drop_column('question_user_invite', 'status')
    # ### end Alembic commands ###
