"""new migrate on 2021-03-27

Revision ID: aeca208090dc
Revises: bc373df5ca2c
Create Date: 2021-03-28 10:43:46.003948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeca208090dc'
down_revision = 'bc373df5ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('post', sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('post_comment', sa.Column('favorite_count', sa.Integer(), nullable=True))
    op.alter_column('question_user_invite', 'status',
                    existing_type=mysql.SMALLINT(),
                    comment='Determine the status of the invited question (0: unanswered, 1: answered, 2: declined)',
                    existing_comment='Trạng thái của câu hỏi cho biết đã được trả lời hay chưa (0: chưa trả lời, 1: đã trả lời, 2: từ chối trả lời)',
                    existing_nullable=True)
    op.alter_column('user', 'is_first_log_in',
                    existing_type=mysql.SMALLINT(),
                    comment='Determine if this is the first time user logged in (0: No, 1: Yes)',
                    existing_comment='Cho biết có phải user login làn đầu hay không (0: không, 1: phải)',
                    existing_nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.drop_column('user', 'allow_answer_comment')
    op.drop_column('user', 'allow_article_comment')
    op.drop_column('user', 'allow_question_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('allow_question_comment', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"),
                            autoincrement=False, nullable=False))
    op.add_column('user',
                  sa.Column('allow_article_comment', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"),
                            autoincrement=False, nullable=False))
    op.add_column('user',
                  sa.Column('allow_answer_comment', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"),
                            autoincrement=False, nullable=False))
    op.alter_column('user', 'is_first_log_in',
                    existing_type=mysql.SMALLINT(),
                    comment='Cho biết có phải user login làn đầu hay không (0: không, 1: phải)',
                    existing_comment='Determine if this is the first time user logged in (0: No, 1: Yes)',
                    existing_nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('question_user_invite', 'status',
                    existing_type=mysql.SMALLINT(),
                    comment='Trạng thái của câu hỏi cho biết đã được trả lời hay chưa (0: chưa trả lời, 1: đã trả lời, 2: từ chối trả lời)',
                    existing_comment='Determine the status of the invited question (0: unanswered, 1: answered, 2: declined)',
                    existing_nullable=True)
    op.drop_column('post_comment', 'favorite_count')
    op.drop_column('post', 'favorite_count')
    op.drop_column('article', 'allow_comments')
    # ### end Alembic commands ###
