"""empty message

Revision ID: b7a33bc47729
Revises: 853626c2595a
Create Date: 2021-04-11 09:35:16.674162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a33bc47729'
down_revision = '853626c2595a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_seen_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_posts_post_id'), 'user_seen_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_user_seen_posts_user_id'), 'user_seen_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_seen_posts_user_id'), table_name='user_seen_posts')
    op.drop_index(op.f('ix_user_seen_posts_post_id'), table_name='user_seen_posts')
    op.drop_table('user_seen_posts')
    # ### end Alembic commands ###
