"""empty message

Revision ID: bc373df5ca2c
Revises: c9f6e5b17120
Create Date: 2021-03-26 22:11:48.942235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc373df5ca2c'
down_revision = 'c9f6e5b17120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_follow', 'is_approved')
    op.drop_column('user_follow', 'is_approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_follow', sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('topic_follow', sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
