"""set default not send email to user

Revision ID: c9f6e5b17120
Revises: 9f93f812e0fd
Create Date: 2021-03-17 11:51:12.757811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9f6e5b17120'
down_revision = '9f93f812e0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'follow_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'1'"),
                    server_default=sa.text("'0'"))
    op.alter_column('user', 'followed_new_publication_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'1'"),
                    server_default=sa.text("'0'"))
    op.alter_column('user', 'new_answer_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'1'"),
                    server_default=sa.text("'0'"))
    op.alter_column('user', 'new_article_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'1'"),
                    server_default=sa.text("'0'"))
    op.alter_column('user', 'new_question_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'1'"),
                    server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'new_question_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"),
                    server_default=sa.text("'1'"))
    op.alter_column('user', 'new_article_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"),
                    server_default=sa.text("'1'"))
    op.alter_column('user', 'new_answer_comment_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"),
                    server_default=sa.text("'1'"))
    op.alter_column('user', 'followed_new_publication_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"),
                    server_default=sa.text("'1'"))
    op.alter_column('user', 'follow_email_settings',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"),
                    server_default=sa.text("'1'"))
    # ### end Alembic commands ###
