"""empty message

Revision ID: cf915c322da9
Revises: 
Create Date: 2020-08-14 15:59:39.378795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf915c322da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('inappropriate', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('inappropriate', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_currently_work', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=False),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('user_hidden', sa.Boolean(), nullable=True),
    sa.Column('image_ids', sa.JSON(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_title', 'article', ['title'], unique=False, mysql_length=255)
    op.create_table('article_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_article',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'article_id')
    )
    op.drop_index('id_UNIQUE', table_name='email_address')
    op.drop_table('email_address')
    op.drop_index('id_UNIQUE', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('id_UNIQUE', table_name='follow')
    op.drop_table('follow')
    op.drop_index('id_UNIQUE', table_name='history')
    op.drop_table('history')
    op.drop_index('id_UNIQUE', table_name='message')
    op.drop_table('message')
    op.drop_index('id_UNIQUE', table_name='notification')
    op.drop_table('notification')
    op.drop_index('id_UNIQUE', table_name='notification_content')
    op.drop_table('notification_content')
    op.drop_index('id_UNIQUE', table_name='permission')
    op.drop_table('permission')
    op.drop_index('id_UNIQUE', table_name='reporting')
    op.drop_table('reporting')
    op.drop_table('request_log')
    op.drop_index('id_UNIQUE', table_name='timeline')
    op.drop_table('timeline')
    op.drop_index('id_UNIQUE', table_name='user_permission')
    op.drop_table('user_permission')
    op.drop_index('id_UNIQUE', table_name='answer')
    op.drop_index('blacklisted_on_UNIQUE', table_name='blacklist_tokens')
    op.drop_index('token_id_UNIQUE', table_name='blacklist_tokens')
    op.drop_index('id_UNIQUE', table_name='comment')
    op.drop_column('comment', 'score')
    op.drop_index('id_UNIQUE', table_name='favorite')
    op.drop_index('id_UNIQUE', table_name='question')
    op.alter_column('question_topic', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('question_topic', 'topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('id_UNIQUE', table_name='question_topic')
    op.alter_column('recovery_user', 'email',
               existing_type=mysql.VARCHAR(charset='utf8', length=80),
               nullable=True)
    op.drop_index('id_UNIQUE', table_name='recovery_user')
    op.drop_index('id_UNIQUE', table_name='reputation')
    op.drop_index('share_id_UNIQUE', table_name='share')
    op.drop_index('signup_user_id_UNIQUE', table_name='signup_user')
    op.drop_index('id_UNIQUE', table_name='topic')
    op.add_column('user', sa.Column('answer_report_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('answer_reported_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('question_downvote_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('question_downvoted_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('question_report_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('question_reported_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('question_upvote_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('question_upvoted_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('user_report_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('user_reported_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('user', sa.Column('verification_sms_time', sa.DateTime(), nullable=True))
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'display_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(charset='latin1', length=255),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(charset='latin1', length=128),
               nullable=True)
    op.drop_index('email', table_name='user')
    op.drop_index('id_UNIQUE', table_name='user')
    op.create_unique_constraint(None, 'user', ['display_name'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'website_url')
    op.drop_column('user', 'job_role')
    op.drop_column('user', 'company')
    op.drop_index('id_UNIQUE', table_name='user_topic')
    op.drop_index('id_UNIQUE', table_name='vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_UNIQUE', 'vote', ['id'], unique=True)
    op.create_index('id_UNIQUE', 'user_topic', ['id'], unique=True)
    op.add_column('user', sa.Column('company', mysql.VARCHAR(charset='utf8', length=255), nullable=True))
    op.add_column('user', sa.Column('job_role', mysql.VARCHAR(charset='utf8', length=255), nullable=True))
    op.add_column('user', sa.Column('website_url', mysql.VARCHAR(charset='latin1', length=200), nullable=True))
    op.add_column('user', sa.Column('country', mysql.VARCHAR(charset='utf8', length=100), nullable=True))
    op.add_column('user', sa.Column('city', mysql.VARCHAR(charset='utf8', length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('id_UNIQUE', 'user', ['id'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(charset='latin1', length=128),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(charset='latin1', length=255),
               nullable=False)
    op.alter_column('user', 'display_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('user', 'verification_sms_time')
    op.drop_column('user', 'user_reported_count')
    op.drop_column('user', 'user_report_count')
    op.drop_column('user', 'question_upvoted_count')
    op.drop_column('user', 'question_upvote_count')
    op.drop_column('user', 'question_reported_count')
    op.drop_column('user', 'question_report_count')
    op.drop_column('user', 'question_downvoted_count')
    op.drop_column('user', 'question_downvote_count')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'answer_reported_count')
    op.drop_column('user', 'answer_report_count')
    op.create_index('id_UNIQUE', 'topic', ['id'], unique=True)
    op.create_index('signup_user_id_UNIQUE', 'signup_user', ['id'], unique=True)
    op.create_index('share_id_UNIQUE', 'share', ['id'], unique=True)
    op.create_index('id_UNIQUE', 'reputation', ['id'], unique=True)
    op.create_index('id_UNIQUE', 'recovery_user', ['id'], unique=True)
    op.alter_column('recovery_user', 'email',
               existing_type=mysql.VARCHAR(charset='utf8', length=80),
               nullable=False)
    op.create_index('id_UNIQUE', 'question_topic', ['id'], unique=True)
    op.alter_column('question_topic', 'topic_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('question_topic', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('id_UNIQUE', 'question', ['id'], unique=True)
    op.create_index('id_UNIQUE', 'favorite', ['id'], unique=True)
    op.add_column('comment', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('id_UNIQUE', 'comment', ['id'], unique=True)
    op.create_index('token_id_UNIQUE', 'blacklist_tokens', ['id'], unique=True)
    op.create_index('blacklisted_on_UNIQUE', 'blacklist_tokens', ['blacklisted_on'], unique=True)
    op.create_index('id_UNIQUE', 'answer', ['id'], unique=True)
    op.create_table('user_permission',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'user_permission', ['id'], unique=True)
    op.create_table('timeline',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activity', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'timeline', ['id'], unique=True)
    op.create_table('request_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('country_short', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('country_long', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('isp', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('zipcode', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('timezone', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('netspeed', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('idd_code', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('area_code', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('weather_code', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('weather_name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mcc', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mnc', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mobile_brand', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('elevation', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('usage_type', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('request_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('referrer', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('reporting',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('inappropriate', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'reporting', ['id'], unique=True)
    op.create_table('permission',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('permission_name', mysql.VARCHAR(charset='utf8', length=80), nullable=True),
    sa.Column('description', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'permission', ['id'], unique=True)
    op.create_table('notification_content',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(charset='utf8'), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'notification_content', ['id'], unique=True)
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('content_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('seen_date', mysql.DATETIME(), nullable=True),
    sa.Column('viewed', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('emailed', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'notification', ['id'], unique=True)
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('message', mysql.TEXT(charset='utf8'), nullable=False),
    sa.Column('sent_time', mysql.DATETIME(), nullable=True),
    sa.Column('read_time', mysql.DATETIME(), nullable=True),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'message', ['id'], unique=True)
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('log', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('critical_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'history', ['id'], unique=True)
    op.create_table('follow',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('followed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'follow', ['id'], unique=True)
    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('overall_rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer_quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bandwitdth_quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('support_quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'feedback', ['id'], unique=True)
    op.create_table('email_address',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(charset='utf8', length=80), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id_UNIQUE', 'email_address', ['id'], unique=True)
    op.drop_table('topic_article')
    op.drop_table('article_favorite')
    op.drop_index('idx_article_title', table_name='article')
    op.drop_table('article')
    op.drop_table('user_employment')
    op.drop_table('social_account')
    op.drop_table('report')
    op.drop_table('article_vote')
    op.drop_table('article_report')
    op.drop_table('article_comment')
    # ### end Alembic commands ###
