"""update post table to add poll

Revision ID: 189452bd8616
Revises: 
Create Date: 2021-04-21 23:23:03.293797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189452bd8616'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_account_user_id'), 'social_account', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Unicode(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('verification_sms_time', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('middle_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('cover_pic_url', sa.String(length=255), nullable=True),
    sa.Column('document_pic_url', sa.String(length=255), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('reputation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('profile_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('show_nsfw', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deactivated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_first_log_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_birthday_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_document', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('show_fullname_instead_of_display_name', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_answer_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_answer_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('my_question_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('my_question_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_question_comment_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('new_question_comment_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_answer_comment_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_answer_comment_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_article_comment_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('new_article_comment_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('question_invite_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('question_invite_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('follow_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('follow_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('followed_new_publication_notify_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('followed_new_publication_email_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('friend_request_notify_settings', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('friend_request_email_settings', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('admin_interaction_notify_settings', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('admin_interaction_email_settings', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('show_email_publicly_setting', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('hoovada_digests_setting', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hoovada_digests_frequency_setting', sa.Enum('weekly', 'daily', name='frequencysettingenum'), server_default='weekly', nullable=False),
    sa.Column('question_aggregated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_shared_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_upvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_downvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_aggregated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_shared_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_upvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_downvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answer_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_aggregated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_shared_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_upvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_downvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('article_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_aggregated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_shared_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_upvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_downvoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('poll_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_aggregated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_shared_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_favorited_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_favorited_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('topic_follow_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('topic_followed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('topic_created_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_reported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('friends_sent_count', sa.Integer(), nullable=True),
    sa.Column('friend_received_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    op.create_table('user_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_employment_user_id'), 'user_employment', ['user_id'], unique=False)
    op.create_table('article_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_report_article_id'), 'article_report', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_report_user_id'), 'article_report', ['user_id'], unique=False)
    op.create_table('poll_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_report_poll_id'), 'poll_report', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_report_user_id'), 'poll_report', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.create_table('post_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_report_post_id'), 'post_report', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_report_user_id'), 'post_report', ['user_id'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('color_code', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_nsfw', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('endorsers_count', sa.Integer(), nullable=True),
    sa.Column('bookmarkers_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('allow_follow', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_parent_id'), 'topic', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topic_slug'), 'topic', ['slug'], unique=False)
    op.create_index(op.f('ix_topic_user_id'), 'topic', ['user_id'], unique=False)
    op.create_table('user_ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ban_by', sa.String(length=255), nullable=True),
    sa.Column('ban_type', sa.Enum('EMAIL', 'PHONE_NUMBER', name='bantypeenum'), server_default='EMAIL', nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.UnicodeText(), nullable=True),
    sa.Column('primary_major', sa.UnicodeText(), nullable=True),
    sa.Column('secondary_major', sa.UnicodeText(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_education_user_id'), 'user_education', ['user_id'], unique=False)
    op.create_table('user_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_follow_followed_id'), 'user_follow', ['followed_id'], unique=False)
    op.create_index(op.f('ix_user_follow_follower_id'), 'user_follow', ['follower_id'], unique=False)
    op.create_table('user_friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('friended_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['friended_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_friend_friend_id'), 'user_friend', ['friend_id'], unique=False)
    op.create_index(op.f('ix_user_friend_friended_id'), 'user_friend', ['friended_id'], unique=False)
    op.create_table('user_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_language_id'), 'user_language', ['language_id'], unique=False)
    op.create_index(op.f('ix_user_language_user_id'), 'user_language', ['user_id'], unique=False)
    op.create_table('user_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_detail', sa.UnicodeText(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location_user_id'), 'user_location', ['user_id'], unique=False)
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('allow', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permission_permission_id'), 'user_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permission_user_id'), 'user_permission', ['user_id'], unique=False)
    op.create_table('article',
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=False),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_fixed_topic_id'), 'article', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_article_slug'), 'article', ['slug'], unique=False)
    op.create_index(op.f('ix_article_user_id'), 'article', ['user_id'], unique=False)
    op.create_table('poll',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('allow_multiple_user_select', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=False),
    sa.Column('expire_after_seconds', sa.Integer(), server_default='86400', nullable=True),
    sa.Column('is_expire', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('select_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_id'), 'poll', ['user_id'], unique=False)
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_post_id'), 'post_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comment_user_id'), 'post_comment', ['user_id'], unique=False)
    op.create_table('post_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_favorite_user_id'), 'post_favorite', ['user_id'], unique=False)
    op.create_table('post_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_share_post_id'), 'post_share', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_share_user_id'), 'post_share', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('question', sa.UnicodeText(), nullable=True),
    sa.Column('accepted_answer_id', sa.Integer(), nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_video_answer', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('allow_audio_answer', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('answers_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_fixed_topic_id'), 'question', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_question_slug'), 'question', ['slug'], unique=False)
    op.create_index(op.f('ix_question_user_id'), 'question', ['user_id'], unique=False)
    op.create_table('question_proposal',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('question', sa.UnicodeText(), nullable=True),
    sa.Column('accepted_answer_id', sa.Integer(), nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_video_answer', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('allow_audio_answer', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('proposal_created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('proposal_updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_parma_delete', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_proposal_fixed_topic_id'), 'question_proposal', ['fixed_topic_id'], unique=False)
    op.create_index(op.f('ix_question_proposal_question_id'), 'question_proposal', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_proposal_slug'), 'question_proposal', ['slug'], unique=False)
    op.create_index(op.f('ix_question_proposal_user_id'), 'question_proposal', ['user_id'], unique=False)
    op.create_table('reputation',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_topic_id'), 'reputation', ['topic_id'], unique=False)
    op.create_index(op.f('ix_reputation_user_id'), 'reputation', ['user_id'], unique=False)
    op.create_table('topic_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_bookmark_user_id'), 'topic_bookmark', ['user_id'], unique=False)
    op.create_table('topic_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_follow_topic_id'), 'topic_follow', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_follow_user_id'), 'topic_follow', ['user_id'], unique=False)
    op.create_table('topic_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_report_topic_id'), 'topic_report', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_report_user_id'), 'topic_report', ['user_id'], unique=False)
    op.create_table('topic_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_share_topic_id'), 'topic_share', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_share_user_id'), 'topic_share', ['user_id'], unique=False)
    op.create_table('topic_user_endorse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endorsed_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endorsed_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_user_endorse_endorsed_id'), 'topic_user_endorse', ['endorsed_id'], unique=False)
    op.create_index(op.f('ix_topic_user_endorse_topic_id'), 'topic_user_endorse', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_user_endorse_user_id'), 'topic_user_endorse', ['user_id'], unique=False)
    op.create_table('user_seen_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_post_post_id'), 'user_seen_post', ['post_id'], unique=False)
    op.create_index(op.f('ix_user_seen_post_user_id'), 'user_seen_post', ['user_id'], unique=False)
    op.create_table('user_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topic_topic_id'), 'user_topic', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_user_id'), 'user_topic', ['user_id'], unique=False)
    op.create_table('answer',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_improvement', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.Enum('AUDIO', 'VIDEO', name='filetypeenum'), nullable=True),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_education_id', sa.Integer(), nullable=True),
    sa.Column('user_location_id', sa.Integer(), nullable=True),
    sa.Column('user_employment_id', sa.Integer(), nullable=True),
    sa.Column('user_language_id', sa.Integer(), nullable=True),
    sa.Column('user_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_education_id'], ['user_education.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_employment_id'], ['user_employment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_language_id'], ['user_language.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_location_id'], ['user_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_topic_id'], ['user_topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id')
    )
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_user_education_id'), 'answer', ['user_education_id'], unique=False)
    op.create_index(op.f('ix_answer_user_employment_id'), 'answer', ['user_employment_id'], unique=False)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_user_language_id'), 'answer', ['user_language_id'], unique=False)
    op.create_index(op.f('ix_answer_user_location_id'), 'answer', ['user_location_id'], unique=False)
    op.create_index(op.f('ix_answer_user_topic_id'), 'answer', ['user_topic_id'], unique=False)
    op.create_table('article_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_bookmark_user_id'), 'article_bookmark', ['user_id'], unique=False)
    op.create_table('article_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_comment_article_id'), 'article_comment', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_comment_user_id'), 'article_comment', ['user_id'], unique=False)
    op.create_table('article_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_favorite_user_id'), 'article_favorite', ['user_id'], unique=False)
    op.create_table('article_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_share_article_id'), 'article_share', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_share_user_id'), 'article_share', ['user_id'], unique=False)
    op.create_table('article_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_vote_article_id'), 'article_vote', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_vote_user_id'), 'article_vote', ['user_id'], unique=False)
    op.create_table('poll_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_bookmark_user_id'), 'poll_bookmark', ['user_id'], unique=False)
    op.create_table('poll_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_poll_id'), 'poll_comment', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_user_id'), 'poll_comment', ['user_id'], unique=False)
    op.create_table('poll_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_favorite_user_id'), 'poll_favorite', ['user_id'], unique=False)
    op.create_table('poll_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('select_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_select_poll_id'), 'poll_select', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_select_user_id'), 'poll_select', ['user_id'], unique=False)
    op.create_table('poll_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_share_poll_id'), 'poll_share', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_share_user_id'), 'poll_share', ['user_id'], unique=False)
    op.create_table('poll_topic',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_topic_poll_id'), 'poll_topic', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_topic_topic_id'), 'poll_topic', ['topic_id'], unique=False)
    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_vote_poll_id'), 'poll_vote', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_vote_user_id'), 'poll_vote', ['user_id'], unique=False)
    op.create_table('post_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('post_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_comment_id'], ['post_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_favorite_user_id'), 'post_comment_favorite', ['user_id'], unique=False)
    op.create_table('post_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_report_comment_id'), 'post_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_post_comment_report_user_id'), 'post_comment_report', ['user_id'], unique=False)
    op.create_table('question_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bookmark_user_id'), 'question_bookmark', ['user_id'], unique=False)
    op.create_table('question_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_comment_question_id'), 'question_comment', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_comment_user_id'), 'question_comment', ['user_id'], unique=False)
    op.create_table('question_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_favorite_user_id'), 'question_favorite', ['user_id'], unique=False)
    op.create_table('question_proposal_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_proposal_id'], ['question_proposal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_report_question_id'), 'question_report', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_report_user_id'), 'question_report', ['user_id'], unique=False)
    op.create_table('question_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_shared_to_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_shared_to_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_share_question_id'), 'question_share', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_share_user_id'), 'question_share', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_share_user_shared_to_id'), 'question_share', ['user_shared_to_id'], unique=False)
    op.create_table('question_topic',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE')
    )
    op.create_table('question_user_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True, comment='Determine the status of the invited question (0: unanswered, 1: answered, 2: declined)'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_vote_question_id'), 'question_vote', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_vote_user_id'), 'question_vote', ['user_id'], unique=False)
    op.create_table('topic_article',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'article_id')
    )
    op.create_table('user_mailed_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mailed_article_article_id'), 'user_mailed_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_article_user_id'), 'user_mailed_article', ['user_id'], unique=False)
    op.create_table('user_mailed_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mailed_question_question_id'), 'user_mailed_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_mailed_question_user_id'), 'user_mailed_question', ['user_id'], unique=False)
    op.create_table('user_seen_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_article_article_id'), 'user_seen_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_seen_article_user_id'), 'user_seen_article', ['user_id'], unique=False)
    op.create_table('user_seen_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_poll_poll_id'), 'user_seen_poll', ['poll_id'], unique=False)
    op.create_index(op.f('ix_user_seen_poll_user_id'), 'user_seen_poll', ['user_id'], unique=False)
    op.create_table('user_seen_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_question_question_id'), 'user_seen_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_seen_question_user_id'), 'user_seen_question', ['user_id'], unique=False)
    op.create_table('answer_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_bookmark_user_id'), 'answer_bookmark', ['user_id'], unique=False)
    op.create_table('answer_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_comment_answer_id'), 'answer_comment', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_user_id'), 'answer_comment', ['user_id'], unique=False)
    op.create_table('answer_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_favorite_user_id'), 'answer_favorite', ['user_id'], unique=False)
    op.create_table('answer_improvement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('vote_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_improvement_answer_id'), 'answer_improvement', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_user_id'), 'answer_improvement', ['user_id'], unique=False)
    op.create_table('answer_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_report_answer_id'), 'answer_report', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_report_user_id'), 'answer_report', ['user_id'], unique=False)
    op.create_table('answer_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_share_answer_id'), 'answer_share', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_share_user_id'), 'answer_share', ['user_id'], unique=False)
    op.create_table('answer_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_vote_answer_id'), 'answer_vote', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_vote_user_id'), 'answer_vote', ['user_id'], unique=False)
    op.create_table('article_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('article_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_comment_id'], ['article_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_comment_favorite_user_id'), 'article_comment_favorite', ['user_id'], unique=False)
    op.create_table('article_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['article_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_comment_report_comment_id'), 'article_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_article_comment_report_user_id'), 'article_comment_report', ['user_id'], unique=False)
    op.create_table('poll_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_favorite_user_id'), 'poll_comment_favorite', ['user_id'], unique=False)
    op.create_table('poll_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_report_comment_id'), 'poll_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_report_user_id'), 'poll_comment_report', ['user_id'], unique=False)
    op.create_table('poll_user_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_select_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_select_id'], ['poll_select.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_select_poll_select_id'), 'poll_user_select', ['poll_select_id'], unique=False)
    op.create_index(op.f('ix_poll_user_select_user_id'), 'poll_user_select', ['user_id'], unique=False)
    op.create_table('question_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('question_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_comment_id'], ['question_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_comment_favorite_user_id'), 'question_comment_favorite', ['user_id'], unique=False)
    op.create_table('question_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['question_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_comment_report_comment_id'), 'question_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_question_comment_report_user_id'), 'question_comment_report', ['user_id'], unique=False)
    op.create_table('answer_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('answer_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_comment_id'], ['answer_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_comment_favorite_user_id'), 'answer_comment_favorite', ['user_id'], unique=False)
    op.create_table('answer_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['answer_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_comment_report_comment_id'), 'answer_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_answer_comment_report_user_id'), 'answer_comment_report', ['user_id'], unique=False)
    op.create_table('answer_improvement_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('improvement_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['improvement_id'], ['answer_improvement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_improvement_vote_improvement_id'), 'answer_improvement_vote', ['improvement_id'], unique=False)
    op.create_index(op.f('ix_answer_improvement_vote_user_id'), 'answer_improvement_vote', ['user_id'], unique=False)
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_comment_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('answer_comment_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('article_comment_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('poll_comment_id', sa.Integer(), nullable=True),
    sa.Column('activity', sa.Enum('COMMENTED', 'FAVORITED', 'UPVOTED', 'DOWNVOTED', 'REPORTED', name='timelineactivityenum'), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_comment_id'], ['answer_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_comment_id'], ['article_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_comment_id'], ['question_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_answer_id'), 'timeline', ['answer_id'], unique=False)
    op.create_index(op.f('ix_timeline_article_id'), 'timeline', ['article_id'], unique=False)
    op.create_index(op.f('ix_timeline_poll_id'), 'timeline', ['poll_id'], unique=False)
    op.create_index(op.f('ix_timeline_question_id'), 'timeline', ['question_id'], unique=False)
    op.create_index(op.f('ix_timeline_user_id'), 'timeline', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_user_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_question_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_poll_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_article_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_answer_id'), table_name='timeline')
    op.drop_table('timeline')
    op.drop_index(op.f('ix_answer_improvement_vote_user_id'), table_name='answer_improvement_vote')
    op.drop_index(op.f('ix_answer_improvement_vote_improvement_id'), table_name='answer_improvement_vote')
    op.drop_table('answer_improvement_vote')
    op.drop_index(op.f('ix_answer_comment_report_user_id'), table_name='answer_comment_report')
    op.drop_index(op.f('ix_answer_comment_report_comment_id'), table_name='answer_comment_report')
    op.drop_table('answer_comment_report')
    op.drop_index(op.f('ix_answer_comment_favorite_user_id'), table_name='answer_comment_favorite')
    op.drop_table('answer_comment_favorite')
    op.drop_index(op.f('ix_question_comment_report_user_id'), table_name='question_comment_report')
    op.drop_index(op.f('ix_question_comment_report_comment_id'), table_name='question_comment_report')
    op.drop_table('question_comment_report')
    op.drop_index(op.f('ix_question_comment_favorite_user_id'), table_name='question_comment_favorite')
    op.drop_table('question_comment_favorite')
    op.drop_index(op.f('ix_poll_user_select_user_id'), table_name='poll_user_select')
    op.drop_index(op.f('ix_poll_user_select_poll_select_id'), table_name='poll_user_select')
    op.drop_table('poll_user_select')
    op.drop_index(op.f('ix_poll_comment_report_user_id'), table_name='poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_report_comment_id'), table_name='poll_comment_report')
    op.drop_table('poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_favorite_user_id'), table_name='poll_comment_favorite')
    op.drop_table('poll_comment_favorite')
    op.drop_index(op.f('ix_article_comment_report_user_id'), table_name='article_comment_report')
    op.drop_index(op.f('ix_article_comment_report_comment_id'), table_name='article_comment_report')
    op.drop_table('article_comment_report')
    op.drop_index(op.f('ix_article_comment_favorite_user_id'), table_name='article_comment_favorite')
    op.drop_table('article_comment_favorite')
    op.drop_index(op.f('ix_answer_vote_user_id'), table_name='answer_vote')
    op.drop_index(op.f('ix_answer_vote_answer_id'), table_name='answer_vote')
    op.drop_table('answer_vote')
    op.drop_index(op.f('ix_answer_share_user_id'), table_name='answer_share')
    op.drop_index(op.f('ix_answer_share_answer_id'), table_name='answer_share')
    op.drop_table('answer_share')
    op.drop_index(op.f('ix_answer_report_user_id'), table_name='answer_report')
    op.drop_index(op.f('ix_answer_report_answer_id'), table_name='answer_report')
    op.drop_table('answer_report')
    op.drop_index(op.f('ix_answer_improvement_user_id'), table_name='answer_improvement')
    op.drop_index(op.f('ix_answer_improvement_answer_id'), table_name='answer_improvement')
    op.drop_table('answer_improvement')
    op.drop_index(op.f('ix_answer_favorite_user_id'), table_name='answer_favorite')
    op.drop_table('answer_favorite')
    op.drop_index(op.f('ix_answer_comment_user_id'), table_name='answer_comment')
    op.drop_index(op.f('ix_answer_comment_answer_id'), table_name='answer_comment')
    op.drop_table('answer_comment')
    op.drop_index(op.f('ix_answer_bookmark_user_id'), table_name='answer_bookmark')
    op.drop_table('answer_bookmark')
    op.drop_index(op.f('ix_user_seen_question_user_id'), table_name='user_seen_question')
    op.drop_index(op.f('ix_user_seen_question_question_id'), table_name='user_seen_question')
    op.drop_table('user_seen_question')
    op.drop_index(op.f('ix_user_seen_poll_user_id'), table_name='user_seen_poll')
    op.drop_index(op.f('ix_user_seen_poll_poll_id'), table_name='user_seen_poll')
    op.drop_table('user_seen_poll')
    op.drop_index(op.f('ix_user_seen_article_user_id'), table_name='user_seen_article')
    op.drop_index(op.f('ix_user_seen_article_article_id'), table_name='user_seen_article')
    op.drop_table('user_seen_article')
    op.drop_index(op.f('ix_user_mailed_question_user_id'), table_name='user_mailed_question')
    op.drop_index(op.f('ix_user_mailed_question_question_id'), table_name='user_mailed_question')
    op.drop_table('user_mailed_question')
    op.drop_index(op.f('ix_user_mailed_article_user_id'), table_name='user_mailed_article')
    op.drop_index(op.f('ix_user_mailed_article_article_id'), table_name='user_mailed_article')
    op.drop_table('user_mailed_article')
    op.drop_table('topic_article')
    op.drop_index(op.f('ix_question_vote_user_id'), table_name='question_vote')
    op.drop_index(op.f('ix_question_vote_question_id'), table_name='question_vote')
    op.drop_table('question_vote')
    op.drop_table('question_user_invite')
    op.drop_table('question_topic')
    op.drop_index(op.f('ix_question_share_user_shared_to_id'), table_name='question_share')
    op.drop_index(op.f('ix_question_share_user_id'), table_name='question_share')
    op.drop_index(op.f('ix_question_share_question_id'), table_name='question_share')
    op.drop_table('question_share')
    op.drop_index(op.f('ix_question_report_user_id'), table_name='question_report')
    op.drop_index(op.f('ix_question_report_question_id'), table_name='question_report')
    op.drop_table('question_report')
    op.drop_table('question_proposal_topic')
    op.drop_index(op.f('ix_question_favorite_user_id'), table_name='question_favorite')
    op.drop_table('question_favorite')
    op.drop_index(op.f('ix_question_comment_user_id'), table_name='question_comment')
    op.drop_index(op.f('ix_question_comment_question_id'), table_name='question_comment')
    op.drop_table('question_comment')
    op.drop_index(op.f('ix_question_bookmark_user_id'), table_name='question_bookmark')
    op.drop_table('question_bookmark')
    op.drop_index(op.f('ix_post_comment_report_user_id'), table_name='post_comment_report')
    op.drop_index(op.f('ix_post_comment_report_comment_id'), table_name='post_comment_report')
    op.drop_table('post_comment_report')
    op.drop_index(op.f('ix_post_comment_favorite_user_id'), table_name='post_comment_favorite')
    op.drop_table('post_comment_favorite')
    op.drop_index(op.f('ix_poll_vote_user_id'), table_name='poll_vote')
    op.drop_index(op.f('ix_poll_vote_poll_id'), table_name='poll_vote')
    op.drop_table('poll_vote')
    op.drop_index(op.f('ix_poll_topic_topic_id'), table_name='poll_topic')
    op.drop_index(op.f('ix_poll_topic_poll_id'), table_name='poll_topic')
    op.drop_table('poll_topic')
    op.drop_index(op.f('ix_poll_share_user_id'), table_name='poll_share')
    op.drop_index(op.f('ix_poll_share_poll_id'), table_name='poll_share')
    op.drop_table('poll_share')
    op.drop_index(op.f('ix_poll_select_user_id'), table_name='poll_select')
    op.drop_index(op.f('ix_poll_select_poll_id'), table_name='poll_select')
    op.drop_table('poll_select')
    op.drop_index(op.f('ix_poll_favorite_user_id'), table_name='poll_favorite')
    op.drop_table('poll_favorite')
    op.drop_index(op.f('ix_poll_comment_user_id'), table_name='poll_comment')
    op.drop_index(op.f('ix_poll_comment_poll_id'), table_name='poll_comment')
    op.drop_table('poll_comment')
    op.drop_index(op.f('ix_poll_bookmark_user_id'), table_name='poll_bookmark')
    op.drop_table('poll_bookmark')
    op.drop_index(op.f('ix_article_vote_user_id'), table_name='article_vote')
    op.drop_index(op.f('ix_article_vote_article_id'), table_name='article_vote')
    op.drop_table('article_vote')
    op.drop_index(op.f('ix_article_share_user_id'), table_name='article_share')
    op.drop_index(op.f('ix_article_share_article_id'), table_name='article_share')
    op.drop_table('article_share')
    op.drop_index(op.f('ix_article_favorite_user_id'), table_name='article_favorite')
    op.drop_table('article_favorite')
    op.drop_index(op.f('ix_article_comment_user_id'), table_name='article_comment')
    op.drop_index(op.f('ix_article_comment_article_id'), table_name='article_comment')
    op.drop_table('article_comment')
    op.drop_index(op.f('ix_article_bookmark_user_id'), table_name='article_bookmark')
    op.drop_table('article_bookmark')
    op.drop_index(op.f('ix_answer_user_topic_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_user_location_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_user_language_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_user_employment_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_user_education_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_user_topic_user_id'), table_name='user_topic')
    op.drop_index(op.f('ix_user_topic_topic_id'), table_name='user_topic')
    op.drop_table('user_topic')
    op.drop_index(op.f('ix_user_seen_post_user_id'), table_name='user_seen_post')
    op.drop_index(op.f('ix_user_seen_post_post_id'), table_name='user_seen_post')
    op.drop_table('user_seen_post')
    op.drop_index(op.f('ix_topic_user_endorse_user_id'), table_name='topic_user_endorse')
    op.drop_index(op.f('ix_topic_user_endorse_topic_id'), table_name='topic_user_endorse')
    op.drop_index(op.f('ix_topic_user_endorse_endorsed_id'), table_name='topic_user_endorse')
    op.drop_table('topic_user_endorse')
    op.drop_index(op.f('ix_topic_share_user_id'), table_name='topic_share')
    op.drop_index(op.f('ix_topic_share_topic_id'), table_name='topic_share')
    op.drop_table('topic_share')
    op.drop_index(op.f('ix_topic_report_user_id'), table_name='topic_report')
    op.drop_index(op.f('ix_topic_report_topic_id'), table_name='topic_report')
    op.drop_table('topic_report')
    op.drop_index(op.f('ix_topic_follow_user_id'), table_name='topic_follow')
    op.drop_index(op.f('ix_topic_follow_topic_id'), table_name='topic_follow')
    op.drop_table('topic_follow')
    op.drop_index(op.f('ix_topic_bookmark_user_id'), table_name='topic_bookmark')
    op.drop_table('topic_bookmark')
    op.drop_index(op.f('ix_reputation_user_id'), table_name='reputation')
    op.drop_index(op.f('ix_reputation_topic_id'), table_name='reputation')
    op.drop_table('reputation')
    op.drop_index(op.f('ix_question_proposal_user_id'), table_name='question_proposal')
    op.drop_index(op.f('ix_question_proposal_slug'), table_name='question_proposal')
    op.drop_index(op.f('ix_question_proposal_question_id'), table_name='question_proposal')
    op.drop_index(op.f('ix_question_proposal_fixed_topic_id'), table_name='question_proposal')
    op.drop_table('question_proposal')
    op.drop_index(op.f('ix_question_user_id'), table_name='question')
    op.drop_index(op.f('ix_question_slug'), table_name='question')
    op.drop_index(op.f('ix_question_fixed_topic_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_post_share_user_id'), table_name='post_share')
    op.drop_index(op.f('ix_post_share_post_id'), table_name='post_share')
    op.drop_table('post_share')
    op.drop_index(op.f('ix_post_favorite_user_id'), table_name='post_favorite')
    op.drop_table('post_favorite')
    op.drop_index(op.f('ix_post_comment_user_id'), table_name='post_comment')
    op.drop_index(op.f('ix_post_comment_post_id'), table_name='post_comment')
    op.drop_table('post_comment')
    op.drop_index(op.f('ix_poll_user_id'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_article_user_id'), table_name='article')
    op.drop_index(op.f('ix_article_slug'), table_name='article')
    op.drop_index(op.f('ix_article_fixed_topic_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_permission_user_id'), table_name='user_permission')
    op.drop_index(op.f('ix_user_permission_permission_id'), table_name='user_permission')
    op.drop_table('user_permission')
    op.drop_index(op.f('ix_user_location_user_id'), table_name='user_location')
    op.drop_table('user_location')
    op.drop_index(op.f('ix_user_language_user_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_language_language_id'), table_name='user_language')
    op.drop_table('user_language')
    op.drop_index(op.f('ix_user_friend_friended_id'), table_name='user_friend')
    op.drop_index(op.f('ix_user_friend_friend_id'), table_name='user_friend')
    op.drop_table('user_friend')
    op.drop_index(op.f('ix_user_follow_follower_id'), table_name='user_follow')
    op.drop_index(op.f('ix_user_follow_followed_id'), table_name='user_follow')
    op.drop_table('user_follow')
    op.drop_index(op.f('ix_user_education_user_id'), table_name='user_education')
    op.drop_table('user_education')
    op.drop_table('user_ban')
    op.drop_index(op.f('ix_topic_user_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_slug'), table_name='topic')
    op.drop_index(op.f('ix_topic_parent_id'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_post_report_user_id'), table_name='post_report')
    op.drop_index(op.f('ix_post_report_post_id'), table_name='post_report')
    op.drop_table('post_report')
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_poll_report_user_id'), table_name='poll_report')
    op.drop_index(op.f('ix_poll_report_poll_id'), table_name='poll_report')
    op.drop_table('poll_report')
    op.drop_index(op.f('ix_article_report_user_id'), table_name='article_report')
    op.drop_index(op.f('ix_article_report_article_id'), table_name='article_report')
    op.drop_table('article_report')
    op.drop_index(op.f('ix_user_employment_user_id'), table_name='user_employment')
    op.drop_table('user_employment')
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_social_account_user_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_table('permission')
    op.drop_table('language')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
