"""add version v0.7.0

Revision ID: 72a0413a2b1d
Revises: initial
Create Date: 2021-04-18 22:38:36.432812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72a0413a2b1d'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_report_poll_id'), 'poll_report', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_report_user_id'), 'poll_report', ['user_id'], unique=False)
    op.create_table('poll',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('allow_multiple_user_select', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixed_topic_id', sa.Integer(), nullable=False),
    sa.Column('expire_after_seconds', sa.Integer(), server_default='86400', nullable=True),
    sa.Column('is_expire', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('select_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['fixed_topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_id'), 'poll', ['user_id'], unique=False)
    op.create_table('user_seen_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_post_post_id'), 'user_seen_post', ['post_id'], unique=False)
    op.create_index(op.f('ix_user_seen_post_user_id'), 'user_seen_post', ['user_id'], unique=False)
    op.create_table('article_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_bookmark_user_id'), 'article_bookmark', ['user_id'], unique=False)
    op.create_table('poll_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_bookmark_user_id'), 'poll_bookmark', ['user_id'], unique=False)
    op.create_table('poll_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('allow_favorite', sa.Boolean(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_poll_id'), 'poll_comment', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_user_id'), 'poll_comment', ['user_id'], unique=False)
    op.create_table('poll_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_favorite_user_id'), 'poll_favorite', ['user_id'], unique=False)
    op.create_table('poll_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('select_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_select_poll_id'), 'poll_select', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_select_user_id'), 'poll_select', ['user_id'], unique=False)
    op.create_table('poll_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('zalo', sa.Boolean(), nullable=True),
    sa.Column('vkontakte', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.Column('link_copied', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_share_poll_id'), 'poll_share', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_share_user_id'), 'poll_share', ['user_id'], unique=False)
    op.create_table('poll_topic',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_topic_poll_id'), 'poll_topic', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_topic_topic_id'), 'poll_topic', ['topic_id'], unique=False)
    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_status', sa.Enum('NEUTRAL', 'UPVOTED', 'DOWNVOTED', name='votingstatusenum'), server_default='NEUTRAL', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_vote_poll_id'), 'poll_vote', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_vote_user_id'), 'poll_vote', ['user_id'], unique=False)
    op.create_table('post_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('post_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_comment_id'], ['post_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_favorite_user_id'), 'post_comment_favorite', ['user_id'], unique=False)
    op.create_table('post_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comment_report_comment_id'), 'post_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_post_comment_report_user_id'), 'post_comment_report', ['user_id'], unique=False)
    op.create_table('user_seen_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_seen_poll_poll_id'), 'user_seen_poll', ['poll_id'], unique=False)
    op.create_index(op.f('ix_user_seen_poll_user_id'), 'user_seen_poll', ['user_id'], unique=False)
    op.create_table('poll_comment_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('poll_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_favorite_user_id'), 'poll_comment_favorite', ['user_id'], unique=False)
    op.create_table('poll_comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('GENERAL', 'INAPPROPRIATE', 'DUPLICATE', name='reporttypeenum'), server_default='GENERAL', nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['poll_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_comment_report_comment_id'), 'poll_comment_report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_poll_comment_report_user_id'), 'poll_comment_report', ['user_id'], unique=False)
    op.create_table('poll_user_select',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_select_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_select_id'], ['poll_select.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_user_select_poll_select_id'), 'poll_user_select', ['poll_select_id'], unique=False)
    op.create_index(op.f('ix_poll_user_select_user_id'), 'poll_user_select', ['user_id'], unique=False)
    op.drop_constraint('post_vote_ibfk_1', 'post_vote', type_='foreignkey')
    op.drop_constraint('post_vote_ibfk_2', 'post_vote', type_='foreignkey')
    op.drop_index('ix_post_vote_post_id', table_name='post_vote')
    op.drop_index('ix_post_vote_user_id', table_name='post_vote')
    op.drop_table('post_vote')
    op.drop_table('topic_post')
    op.add_column('answer', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('answer', sa.Column('user_education_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answer_user_education_id'), 'answer', ['user_education_id'], unique=False)
    op.create_foreign_key(None, 'answer', 'user_education', ['user_education_id'], ['id'], ondelete='CASCADE')
    op.add_column('article', sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('post', sa.Column('allow_comments', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('post', sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('post', 'comment_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('post', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_index('ix_post_fixed_topic_id', table_name='post')
    op.drop_column('post', 'fixed_topic_id')
    op.drop_column('post', 'downvote_count')
    op.drop_column('post', 'upvote_count')
    op.add_column('post_comment', sa.Column('favorite_count', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('question_proposal', sa.Column('allow_voting', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('question_user_invite', sa.Column('id', sa.Integer(), nullable=False))
    op.execute("ALTER TABLE hoovada.`question_user_invite` ADD INDEX(`id`)")
    op.execute("ALTER TABLE hoovada.`question_user_invite` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT")
    op.add_column('question_user_invite', sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True, comment='Determine the status of the invited question (0: unanswered, 1: answered, 2: declined)'))
    op.add_column('timeline', sa.Column('poll_comment_id', sa.Integer(), nullable=True))
    op.add_column('timeline', sa.Column('poll_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timeline_poll_id'), 'timeline', ['poll_id'], unique=False)
    op.create_foreign_key(None, 'timeline', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timeline', 'poll_comment', ['poll_comment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('topic_follow', 'is_approved')
    op.add_column('user', sa.Column('is_first_log_in', sa.SmallInteger(), server_default='0', nullable=True, comment='Determine if this is the first time user logged in (0: No, 1: Yes)'))
    op.add_column('user', sa.Column('show_fullname_instead_of_display_name', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.add_column('user_education', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_employment', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.drop_column('user_follow', 'is_approved')
    op.add_column('user_language', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_location', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('user_topic', sa.Column('is_visible', sa.Boolean(), nullable=True))

    op.add_column('answer', sa.Column('user_employment_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('user_language_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('user_location_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('user_topic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answer_user_employment_id'), 'answer', ['user_employment_id'], unique=False)
    op.create_index(op.f('ix_answer_user_language_id'), 'answer', ['user_language_id'], unique=False)
    op.create_index(op.f('ix_answer_user_location_id'), 'answer', ['user_location_id'], unique=False)
    op.create_index(op.f('ix_answer_user_topic_id'), 'answer', ['user_topic_id'], unique=False)
    op.create_foreign_key(None, 'answer', 'user_location', ['user_location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer', 'user_language', ['user_language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer', 'user_topic', ['user_topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer', 'user_employment', ['user_employment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic', 'is_visible')
    op.drop_column('user_location', 'is_visible')
    op.drop_column('user_language', 'is_visible')
    op.add_column('user_follow', sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_employment', 'is_visible')
    op.drop_column('user_education', 'is_visible')
    op.alter_column('user', 'new_question_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'new_article_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'new_answer_comment_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'followed_new_publication_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'follow_email_settings',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_column('user', 'show_fullname_instead_of_display_name')
    op.drop_column('user', 'is_first_log_in')
    op.add_column('topic_follow', sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.drop_index(op.f('ix_timeline_poll_id'), table_name='timeline')
    op.drop_column('timeline', 'poll_id')
    op.drop_column('timeline', 'poll_comment_id')
    op.drop_column('question_user_invite', 'status')
    op.drop_column('question_user_invite', 'id')
    op.drop_column('question_proposal', 'allow_voting')
    op.drop_column('question', 'allow_voting')
    op.drop_column('post_comment', 'favorite_count')
    op.add_column('post', sa.Column('upvote_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('downvote_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('fixed_topic_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_ibfk_1', 'post', 'topic', ['fixed_topic_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_post_fixed_topic_id', 'post', ['fixed_topic_id'], unique=False)
    op.alter_column('post', 'share_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('post', 'comment_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('post', 'favorite_count')
    op.drop_column('post', 'allow_comments')
    op.drop_column('article', 'allow_comments')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_index(op.f('ix_answer_user_education_id'), table_name='answer')
    op.drop_column('answer', 'user_education_id')
    op.drop_column('answer', 'allow_voting')
    op.create_table('topic_post',
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='topic_post_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='topic_post_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'post_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post_vote',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote_status', mysql.ENUM('NEUTRAL', 'UPVOTED', 'DOWNVOTED'), server_default=sa.text("'NEUTRAL'"), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_vote_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_vote_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_post_vote_user_id', 'post_vote', ['user_id'], unique=False)
    op.create_index('ix_post_vote_post_id', 'post_vote', ['post_id'], unique=False)
    op.drop_index(op.f('ix_poll_user_select_user_id'), table_name='poll_user_select')
    op.drop_index(op.f('ix_poll_user_select_poll_select_id'), table_name='poll_user_select')
    op.drop_table('poll_user_select')
    op.drop_index(op.f('ix_poll_comment_report_user_id'), table_name='poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_report_comment_id'), table_name='poll_comment_report')
    op.drop_table('poll_comment_report')
    op.drop_index(op.f('ix_poll_comment_favorite_user_id'), table_name='poll_comment_favorite')
    op.drop_table('poll_comment_favorite')
    op.drop_index(op.f('ix_user_seen_poll_user_id'), table_name='user_seen_poll')
    op.drop_index(op.f('ix_user_seen_poll_poll_id'), table_name='user_seen_poll')
    op.drop_table('user_seen_poll')
    op.drop_index(op.f('ix_post_comment_report_user_id'), table_name='post_comment_report')
    op.drop_index(op.f('ix_post_comment_report_comment_id'), table_name='post_comment_report')
    op.drop_table('post_comment_report')
    op.drop_index(op.f('ix_post_comment_favorite_user_id'), table_name='post_comment_favorite')
    op.drop_table('post_comment_favorite')
    op.drop_index(op.f('ix_poll_vote_user_id'), table_name='poll_vote')
    op.drop_index(op.f('ix_poll_vote_poll_id'), table_name='poll_vote')
    op.drop_table('poll_vote')
    op.drop_index(op.f('ix_poll_topic_topic_id'), table_name='poll_topic')
    op.drop_index(op.f('ix_poll_topic_poll_id'), table_name='poll_topic')
    op.drop_table('poll_topic')
    op.drop_index(op.f('ix_poll_share_user_id'), table_name='poll_share')
    op.drop_index(op.f('ix_poll_share_poll_id'), table_name='poll_share')
    op.drop_table('poll_share')
    op.drop_index(op.f('ix_poll_select_user_id'), table_name='poll_select')
    op.drop_index(op.f('ix_poll_select_poll_id'), table_name='poll_select')
    op.drop_table('poll_select')
    op.drop_index(op.f('ix_poll_favorite_user_id'), table_name='poll_favorite')
    op.drop_table('poll_favorite')
    op.drop_index(op.f('ix_poll_comment_user_id'), table_name='poll_comment')
    op.drop_index(op.f('ix_poll_comment_poll_id'), table_name='poll_comment')
    op.drop_table('poll_comment')
    op.drop_index(op.f('ix_poll_bookmark_user_id'), table_name='poll_bookmark')
    op.drop_table('poll_bookmark')
    op.drop_index(op.f('ix_article_bookmark_user_id'), table_name='article_bookmark')
    op.drop_table('article_bookmark')
    op.drop_index(op.f('ix_user_seen_post_user_id'), table_name='user_seen_post')
    op.drop_index(op.f('ix_user_seen_post_post_id'), table_name='user_seen_post')
    op.drop_table('user_seen_post')
    op.drop_index(op.f('ix_poll_user_id'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_poll_report_user_id'), table_name='poll_report')
    op.drop_index(op.f('ix_poll_report_poll_id'), table_name='poll_report')
    op.drop_table('poll_report')

    op.drop_column('answer', 'user_topic_id')
    op.drop_column('answer', 'user_location_id')
    op.drop_column('answer', 'user_language_id')
    op.drop_column('answer', 'user_employment_id')
    # ### end Alembic commands ###
